### ISSUE TITLE
Can't connect to IBM i

### ISSUE THREAD

**Issue by Carolla82** [halcyon-tech/code-for-ibmi#100]
When I click on Connect to an IBM i, enter the IP, leave the default port at 22, and enter my user name and password, I get the following error:

'Not connected to n.n.n.n! connect ECONNREFUSED n.n.n.n:22'

where n.n.n.n is the IP of my IBM i. I have tried with both of my IBM systems,  from a PC that is able to connect using IBM i Access. I also tried using the DNS name, and the same error comes up. I verified the profile is enabled.

Is there something that needs to be configured on my IBM i? Any help is appreciated.

**Comment by worksofliam** [comment]
@Carolla82 did you check the read me for the requirements? Did you check the SSH daemon is running?

**Comment by Carolla82** [comment]
@worksofliam Success. I skipped the readme. Thanks!!!
