### ISSUE TITLE
Library list view

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/code-for-ibmi#101]
How about the ability to see and re-order the library list from the Code for IBM i view?

VS Code does not provide an API to allow drag-n-drop of treeitems, so maybe there could be two buttons to move an library up and down - plus also buttons to add and remove.

What do we think?

**Comment by SJLennon** [comment]
Most of my career I've had a basic environment where I set my development library list with a CL program and rarely changed it through the day.  However, from comments I've seen on midrange.com, there are people who are not so fortunate and have need to change the library list. So **support for managing the library list would be a good thing.**  

**Idea:** How about the ability to store library lists by name and to pick one by name.  
Of course, when picked, where would this library list be applied?  All open browsers, or just one browser?  Or maybe you could specify which browser in the supplied list.
