### ISSUE TITLE
add user login variable to action setup

### ISSUE THREAD

**Issue by pydefre** [halcyon-tech/code-for-ibmi#102]
sometimes it may be necessary to have the login name to execute actions

**Comment by worksofliam** [comment]
I will add this tonight!

Just because I am curious, what is the use case here?

**Comment by pydefre** [comment]
to use it with ALDON LMI exits, we need the user who maintains the source. To use it with ALDON LMI exits, we need the user who maintains the source, without having to develop a wrapper

**Comment by worksofliam** [comment]
@pydefre will be available in 0.3.7:

> Add `&USERNAME` as possible action variable

**Comment by pydefre** [comment]
Thanks Barry ! 

Envoyé de mon iPhone
