### ISSUE TITLE
Special rights on the user profile

### ISSUE THREAD

**Issue by pydefre** [halcyon-tech/code-for-ibmi#103]
if the user does not have * ALLOBJ rights, it is impossible to display the source. For security reasons, are specific rights to be defined on the IFS or other parts?

**Comment by worksofliam** [comment]
Is that right?

Check you have access to:

* the source member
* the `CPYTOSTMF` command
* the `/tmp` IFS directory

**Comment by pydefre** [comment]
thanks I check it.

**Comment by worksofliam** [comment]
Please reopen if you have further questions. Thanks!
