### ISSUE TITLE
Multiple setting per environment

### ISSUE THREAD

**Issue by pydefre** [halcyon-tech/code-for-ibmi#104]
It might be a good idea to have a different configuration per environment for the library list, actions which may be different.

**Comment by worksofliam** [comment]
Each connection gets its own library list. Actions are global right now. I don't really understand what you're requesting.

**Comment by pydefre** [comment]
OK, sorry for my poor English. Connection setting is for "one partition" ?. on my DEV partition, i have different data and object environnement, multiple applications.
