### ISSUE TITLE
Member Browser in 0.3.6 Broken?

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/code-for-ibmi#105]
**Describe the bug**
Today I cannot see any members in the member browser. IFS, OBJECT and DATABASE all show objects.  
![image](https://user-images.githubusercontent.com/67484051/110994026-2a909580-8346-11eb-8a71-fee2a0d9aba0.png)

When I click the "Refresh All Member Lists" I see the clock appear on the IBM icon, but no members show up, despite clicking and re-clicking the files.
![image](https://user-images.githubusercontent.com/67484051/110992973-b4d7fa00-8344-11eb-9a83-742ed594c281.png)

**To Reproduce**
1. Click on any member in MEMBER BROWSER.
2. Chevron point down 
3. No members show.

**Expected behavior**
I should see the members.

**Screenshots**
This proves I actually have members...
![image](https://user-images.githubusercontent.com/67484051/110993855-db4a6500-8345-11eb-8d3e-f091c5ad36f5.png)

**Environment (please complete the following information):**
 - Extension version [e.g. 0.3.6]
 - IBM i OS version [e.g. 7.4]

**Additional context**
I'm on PUB400.  Maybe something to do with your changes #91 from DSPFD to SQL?  However, I can run this SQL in SQL Scripts:
![image](https://user-images.githubusercontent.com/67484051/110995162-e1d9dc00-8347-11eb-9d28-fa2fb405fed6.png)

**Comment by worksofliam** [comment]
Recreated it.... 
![image](https://user-images.githubusercontent.com/3708366/110996792-747b7a80-834a-11eb-9c81-2e7c077f8419.png)

Looking into it.

**Comment by worksofliam** [comment]
@SJLennon 

Yes, it has something to do with pub400. I will get hold of them and ask them to upgrade `db2util`.

```
DB2UTIL_JSON_CONTAINER=array /QOpenSys/pkgs/bin/db2util -o json "Select   (Avgrowsize - 12) as MBMXRL,   Iasp_Number as MBASP,   System_Table_Member as MBNAME,   Source_Type as MBSEU2,   Partition_Text as MBMTXT From Qsys2.Syspartitionstat, Qsys2.Sysschemas Where   Table_Schema = 'QSYSINC' And   Table_Name = 'H' And   Schema_Name = System_Table_Schema"
[

]
```

**Comment by worksofliam** [comment]
I guess we will need a way to disable this!

**Comment by SJLennon** [comment]
Maybe in Settings you need a generic "Options" feature that just allows ON or OFF for cases like this.

Sorry to bug you--nothing is simple and no good deed goes unpunished (fixing #91).  I think there is a possibility that PUB400 will have quite a few users.
@worksofliam

**Comment by worksofliam** [comment]
@SJLennon no problem!! Thank you for bringing this to me. I will be releasing this fix very soon. 

I have [asked Holger to update `db2util`](https://twitter.com/notesofbarry/status/1370479071747047427), in the meantime, I added `enableSQL` to the connection settings:

```json
            "homeDirectory": "/home/BARRY",
            "tempLibrary": "BARRY1",
            "buildLibrary": "QTEMP",
            "sourceFileCCSID": "*FILE",
            "enableSQL": false
```

Will be releasing this within the hour.

**Comment by worksofliam** [comment]
@SJLennon 0.3.7 is being deployed.

1. Add `"enableSQL": false` to your connection config
2. Connect to your system
3. Let me know how it goes

**Comment by SJLennon** [comment]
Yep:  That fixed it.  Sterling work!
@worksofliam

**Comment by worksofliam** [comment]
Lovely :)
