### ISSUE TITLE
Member browser drag and drop

### ISSUE THREAD

**Issue by Nope7** [halcyon-tech/code-for-ibmi#110]
It could be great to move source member from a source file to one another with a simple drag-and-drop in order easily organize members in each physical source file.

In a standard IBM i environement, you have to:
1. Copy the member from a source file to another
2. Delete the original member

....it could be easier ;)

**Comment by worksofliam** [comment]
Visual Studio Code does not support drag and drop in TreeView components. It works with file system providers, but we aren't using that due to some performance issues with it and how often it talks to the remote server.

https://github.com/microsoft/vscode/issues/32592
