### ISSUE TITLE
How to edit source code within IASP?

### ISSUE THREAD

**Issue by AjaykulkarniIBMi** [halcyon-tech/code-for-ibmi#111]
**Editing source code within IAAP**
What setup to do in VSCODE to enable editing source code within source file in IASP?

**Comment by worksofliam** [comment]
You can edit the ASP in the additional settings after you have connected.

![image](https://user-images.githubusercontent.com/3708366/111222233-f0c3c700-85b1-11eb-8a54-dd064027a9c8.png)
