### ISSUE TITLE
Log Compile Output - Find Where

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/code-for-ibmi#118]
Possibly this my misunderstanding of VSCODE.
I have "Log Compile Output" set to true, but I can never find the compile listing. After a CRTBNDRPG the OUTPUT tab is empty.
![image](https://user-images.githubusercontent.com/67484051/112348858-9952e480-8c9e-11eb-9b6a-2e35f5dbf574.png)

**_Am I looking in the wrong place?_**

I'm on PUB400 and default on CRTBNDRPG is OUTPUT(*PRINT), so a spool file should be created.

**Comment by worksofliam** [comment]
No problem! Click on the dropdown that says 'Tasks', and you should see 'IBM i Compile Output' or something like that!

**Comment by SJLennon** [comment]
Well Duh!  Never looked at OUTPUT before.  Learned something new today 😃 
I'll try to update the documentation for others like me...

For now. here's a picture:
![image](https://user-images.githubusercontent.com/67484051/112366615-69600d00-8caf-11eb-8175-aecb405c3cbe.png)

**Comment by SJLennon** [comment]
I put in a pull request for updated documentation.

Also, you should probably change this too.  Maybe to "**... OUTPUT tab, IBM i Output**".
![image](https://user-images.githubusercontent.com/67484051/112388205-31fe5a00-8cc9-11eb-94db-fc3e226d3f37.png)

**Comment by SJLennon** [comment]
It seems like my compile listings are coming out double spaced, more or less.  Looks like each line number is duplicated and the second of the pair is blank.  Ring any bells?
![image](https://user-images.githubusercontent.com/67484051/113447463-eb46e900-93c7-11eb-832d-9c4923a5d2a0.png)
Code looks like this:
![image](https://user-images.githubusercontent.com/67484051/113447597-2fd28480-93c8-11eb-8267-3f125243fc81.png)

**Comment by SJLennon** [comment]
Hmm.  Apparently I can't reopen this issue... But not urgent.
@worksofliam

**Comment by worksofliam** [comment]
@SJLennon Sounds like a line ending issue - you're on Windows, which I think uses CRLF by default.

You can change that. See this answer on SO: https://stackoverflow.com/a/39532890/4763757
