### ISSUE TITLE
Connections have unique names instead of using host/IP

### ISSUE THREAD

**Issue by robw7** [halcyon-tech/code-for-ibmi#119]
The Incorrect connection settings from the "code-for-ibmi.connectionSettings" array are used when multiple connections to the same Host System are defined in the “code-for-ibmi.connections" array.

The problem does not occur if the “CASE” of the host names is different.

Example 
Problem occurs when connections are defined as 1) user1@pub400 and 2) user2@pub400.
But does not occur when connections are defined as 1) user1@pub400 and 2) user2@PUB400.

I’m Using version 0.4.1.

Might be nice if I could give the connection and connsectionSettings names.  This would solve the above issue and allow multiple connections to share the same settings.   See below.

"code-for-ibmi.connectionSettings": [
        {
            "connectionSettingsName": "config1",
            "sourceFileList": [
                "TESTLIB/QRPGLESC"
            ]
        },
        {
            "connectionSettingsName": "config2",
            "sourceFileList": [
                "USERLIB/QRPGLESC"
            ]
        }
    ],
    "code-for-ibmi.connections": [
        {
         "name": "connection1",
            "host": "pub400",
            "port": 22,
            "username": "userx",
            "privateKey": null,
	"useConnectionSettingsName": "config1"
        },
        {
         "name": "connection2",
            "host": "pub400",
            "port": 22,
            "username": "usery",
            "privateKey": null
           "useConnectionSettingsName": "config2"
        },
        {
        "name": "connection3",
            "host": "pub400",
            "port": 22,
            "username": "userz",
            "privateKey": null,
	"useConnectionSettingsName": "config1"
        }
    ],
		`
This might also address solve issue “Multiple setting per environment #104”.

Maybe a future enhancement could allow the connection settings from a different name to be dynamically selected without disconnecting.

**Comment by worksofliam** [comment]
Yes, it might be a good idea. It's one of those things which I will need to sit down and actually do - since another change of the configuration could be breaking.

I will look into it, thanks!

**Comment by priceaj** [comment]
FYI I am working on a connections pane and have had to implement this in order to make it sensible, the commit is sat on top of the initial connection pane work, so is unfortunately not self contained, and can't be cherry picked

**Comment by priceaj** [comment]
PR #128 Implemented this as a feature because I require it for another feature I am working on, so split out as per the 1 feature perr PR rule
