### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/code-for-ibmi#12]
We need documentation in either HTML format or markdown (preferred).

Docs should live in the `docs` folder in the root.

The following items need documenting:

* [ ] Login process. New login OR previous login
* [ ] The settings. What each of them means
* [ ] Loading members. How to add more source files
* [ ] Opening source members
* [ ] How to compile sources 
* [ ] How to configure the compile settings

**Comment by ashwindevx** [comment]
Hi! I'm very new to this Open Source world. I was wondering if you need documentation in markdown of README.md or anything else because it looks fine for me.

I mean it looked like a good markdown. So what change do you want?

**Comment by worksofliam** [comment]
Hi @ashwindevx 

Thanks for your interest! It does take a bit of knowledge I suppose, but I updated the original message with the items which need documenting.

**Comment by barrettotte** [comment]
@worksofliam Do you think Docsify would be a decent candidate for the markdown solution ? I've only used it [once](https://barrettotte.github.io/IBMi-Book/#/) in the past. I haven't explored any other options so far. 

I had these links laying in a notes file :

- https://docsify.js.org/#/quickstart
- https://docsify.js.org/#/deploy
- https://github.com/MichaelCurrin/docsify-js-tutorial

**Comment by worksofliam** [comment]
@barrettotte That'd be awesome! I see it can use the `docs` folder also - which is perfect.

**Comment by worksofliam** [comment]
I am starting to think a simple gh-pages might do the trick.. just to get started.

**Comment by worksofliam** [comment]
Thanks to @barrettotte for tackling this. I also made it part of the PR requirements that they update the docs.
