### ISSUE TITLE
Object Browser: Run Action - Call program

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/code-for-ibmi#121]
**Ruminating** on the usefulness of "Call program", since you can't see the results (at least I can't).
  
Call won't do anything for a green screen interactive job.  So it is limited to batch jobs, but how would you look at any printed output, or the job log?

I'm sure there are cases I haven't thought of where "Call program" is useful.  The case where I tried using it I wanted to see the spooled printer output.  

It seems quite tricky to find spooled output created by a server job (QP0ZSPWP).  IBM has some support pages on it. Not sure how you manage it with compiles.

So **maybe we also need a SBMJOB command**, something like this that could be further altered:
`SBMJOB CMD(CALL PGM(LENNONS1/B2))`

Then would you have to handle submitting jobs which have a command other than CALL? For example:
`SBMJOB CMD(DSPJOB OUTPUT(*PRINT) OPTION(*RUNA))`

Just thoughts, and unless a spool file browser turns up the green screen works best.

**Notes for reference, just in case.**
https://www.ibm.com/support/pages/node/641319
https://www.ibm.com/support/pages/finding-and-working-spooled-files-generated-under-qprtjob-job

Seems like I had to solve the problem of spool files from server jobs once in the past, and this is, I believe, how it did it:
`OVRPRTF FILE(*PRTF) SPLFOWN(*CURUSRPRF) OVRSCOPE(*JOB)`

So if I have a program like this:
`             PGM`
`             OVRPRTF FILE(*PRTF) SPLFOWN(*CURUSRPRF) OVRSCOPE(*JOB)`
`             CHGJOB     LOG(4 0 *SECLVL) LOGCLPGM(*YES)`
 `            dsplibl`
 `            DSPJOB     OUTPUT(*PRINT) OPTION(*RUNA)`
 `            ENDPGM
`
I can find my spool files with WRKSPLF.  I don't know if you can do an OVRPRTF that would stick before the call execution.

**Comment by worksofliam** [comment]
> It seems quite tricky to find spooled output created by a server job (QP0ZSPWP).

We have it set so `system` is printing to standard out and not a spool file. [See the command docs here](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_72/rzalf/rzalfpasesystem.htm).

Note that `system` only reads standard out - so `DSPLY` doesn't do anything. The C `printf` function will print to standout out, as will spool files. I hope that is a start to help!
