### ISSUE TITLE
User authorities problem

### ISSUE THREAD

**Issue by pydefre** [halcyon-tech/code-for-ibmi#122]
When I remove the  *ALLOBJ authorities on my profile keeping only :
*IOSYSCFG 
*JOBCTL   
*SAVSYS   
*SERVICE  
*SPLCTL   

I do not see the source members, nothing in the /tmp directory. 
However no problem with IFS Browser, Object Browser and DataBase Browser.

**Comment by SJLennon** [comment]
How about posting a screen shot of VSCODE showing the problem.

Also, show what you can see with WRKLNK that you can't see with VSCODE.
@pydefre

**Comment by pydefre** [comment]
This is the wrklnk screenshot and the vscode source member not showing
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/746599/113890063-20867900-97c4-11eb-93f8-521c24e7b5c1.png)
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/746599/113890068-21b7a600-97c4-11eb-8c65-6f902b662923.png)
<img width="1014" alt="Capture d’écran 2021-04-07 à 17 10 40" src="https://user-images.githubusercontent.com/746599/113890154-33994900-97c4-11eb-9bad-325e3cdf5ebf.png">
<img width="1107" alt="Capture d’écran 2021-04-07 à 17 14 01" src="https://user-images.githubusercontent.com/746599/113890680-ac000a00-97c4-11eb-83b3-2401f6a31036.png">
thanks for your help.

**Comment by SJLennon** [comment]
@pydefre Have a look at issue #105 and see if that helps.

**Comment by SJLennon** [comment]
I have this in my settings:
![image](https://user-images.githubusercontent.com/67484051/113903966-89a7c580-979f-11eb-9db5-5548ebe9a5b1.png)
@pydefre

**Comment by pydefre** [comment]
Thanks ! it works
