### ISSUE TITLE
VSCode constantly says "Initializing JS/TS language features" after opening a JS file in the IFS browser

### ISSUE THREAD

**Issue by sprinkles** [halcyon-tech/code-for-ibmi#123]
VSCode constantly says "Initializing JS/TS language features" after opening a JS file in the IFS browser. It never stops. This might be more of a VSCode problem that I should be reporting elsewhere, but I'm not sure. The files work fine if I make a copy of them locally. I'm just wondering if anyone has seen this issue. 

I was using the SSH FS extension to connect to the files, but I thought I'd switch to this extension. The issue didn't start until I installed this extension, but now it happens when I connect with either one. I didn't install or change anything with the code in the folder that I'm accessing on the IBM i. 

I've completely removed VSCode and the extensions folders from my computer (on a Windows computer, because that's what I have to use at work :( ) and reinstalled everything multiple times, but it is still happening. It's very odd. I've just recently started trying to use a Windows computer for development for the first time since about 2008, so my debugging on it isn't the best. Any ideas would be greatly appreciated! Thanks!

**Comment by SJLennon** [comment]
I see the same thing.  

On Windows 10. It's not taking a lot of CPU time if Task Manager is to be believed.  

If I try to run a simple program with node in VSCODE it says it can't find the program file.  I'm guessing that's because the file isn't in the file system as with most extensions.
![image](https://user-images.githubusercontent.com/67484051/112535210-62ee9580-8d82-11eb-87d4-8d8e2d5bfd5c.png)
@sprinkles

**Comment by worksofliam** [comment]
@sprinkles 

Honestly, I am not quite sure. The languages tools, I assume, don't understand the new file system and therefore don't work with the remote server.

I personally wouldn't recommend writing JavaScript, or TypeScript, on the remote server (IBM i), and instead on the local machine - which is really what Code was meant for (unless you use the Microsoft SSH extension, which actually doesn't work with IBM i).

You can disable this for specific workspaces it looks like: https://stackoverflow.com/a/60026235/4763757

@SJLennon 

> If I try to run a simple program with node in VSCODE it says it can't find the program file. I'm guessing that's because the file isn't in the file system as with most extensions.

Correct. You have to use Node.js on the remote system to run scripts on the remote system.

**Comment by worksofliam** [comment]
@sprinkles I just tested this on my mac.

1. I connect to a system
2. I open a `.js` file in the IFS
3. The 'Initializing JS/TS language features' text shows up for only a few seconds
4. I close the file, and open a different one, and it doesn't show.

I am on a Macbook.

**Comment by worksofliam** [comment]
Hey @sprinkles 

What is the status here? Did you discover anything? I may close this, otherwise.
