### ISSUE TITLE
'db2util' not installed on system message in DATABASE BROWSER

### ISSUE THREAD

**Issue by ajmorsejr** [halcyon-tech/code-for-ibmi#124]
Hi,

Just installed code-for-ibmi and everything seems to work great, except not able to use DATABASE BROWSER because of 'db2util' not installed on system. 

I didn't see this mentioned in the documentation as a prerequisite, but looking through some other tickets it appears db2util needs to be installed. 

Is there a command or some library to look in to determine if that is installed?

**Comment by worksofliam** [comment]
@ajmorsejr Hi!

`db2util` can be installed through yum on your IBM i.
