### ISSUE TITLE
How to connect using V5R4

### ISSUE THREAD

**Issue by tb-mtg** [halcyon-tech/code-for-ibmi#125]
When trying to make a connection we get exception:

> Not connected to {our-ibm-i}! Handshake failed: no matching key exchange algorithm.

Unfortunately our IBM I is is still on V5R4.  

**Is it possible to connect using V5R4?**

**Comment by SJLennon** [comment]
I don't see why it would have a problem with V5R4.  
Were you trying with a Private Key?  If so, how about trying a password?
![image](https://user-images.githubusercontent.com/67484051/113434910-ce9eb700-93af-11eb-8286-92ec9ecb72bc.png)

**Comment by worksofliam** [comment]
@tb-mtg I am highly doubtful this will work with 5.4. Make sure the SSH Daemon is started, and of course.. pase needs to be installed. My knowledge of 5.4 is lacking, but I think we only officially support 7.2 and above.

**Comment by tb-mtg** [comment]
Firstly thanks guys.

### **Some Background**

I understand that only version 7.2 & above is supported. One of the main reasons we wanted to use **[Code for IBM i](https://github.com/halcyon-tech/code-for-ibmi)** is to assist in modernizing our old code (RPG, etc..) to be able to upgrade to a newer version of iSeries (or IBM i) using modern alternative to SEU.  

We also wanted to test moving our source code out of Physical Source File Members into IFS files and possibly even using git down the track.

Unfortunately [IBM Rational Developer for i (RDI)](https://www.ibm.com/support/pages/ibm-rational-developer-i-hub) is just too expensive.  We also tried both [ILEditor](https://github.com/worksofbarry/ILEditor) and [ILEditor2](https://ileditor.dev/).. 

### **Steps Taken**

We have now installed **PASE** and some PTFs related to product ID 5733SC1 and done an IPL over the weekend just gone.

Also have been able to start the **SSH daemon** using these [instructions for v5r4](https://www.ibm.com/support/pages/starting-openssh-server-sshd)
(using CL command `STRTCPSVR *SSHD` is not available until [v6.1](https://www.seidengroup.com/2011/03/11/ssh-on-ibm-i/) and gives error `TCP/IP server *SSHD does not exist`).

Since doing the PASE install and applying the PTFs we are now able to make connections to our system using both **ILEditor** and **ILEditor2** whereas we could not before. 

However we still cannot connect using **Code for IBM i** which now gives a different error:

> _Not connected to {our-ibm-i}! Timed out while waiting for handshake_

We seem so close, is there anything I can do to fix this?

**Comment by SJLennon** [comment]
@tb-mtg This is beyond my expertise, but to aid in further debugging, have you tried to connect using PuTTY?  Or perhaps SSH in Windows.

**Comment by priceaj** [comment]
This looks like an error directly from the ssh2 which is used to connect, you could try connecting with SSH2 and see if you get the same issue. 

You could knock up a quick test program to output a connection log. Something like this:

> var Client = require('ssh2').Client;
> 
>  console.log('Start ssh2...');
>  var conn = new Client();
>  conn.on('ready', function() {
>     console.log('Client :: ready');
>             conn.shell(function(err, stream) {
>               if (err) throw err;
>               stream.on('close', function() {
>                 console.log('Stream :: close');
>                 conn.end();
>               }).on('data', function(data) {
>                 console.log('STDOUT: ' + data);
>               }).stderr.on('data', function(data) {
>                 console.log('STDERR: ' + data);
>               });
>               stream.end('ls -l\nexit\n');
>             });
>  }).connect({
>    host: 'pub400.com',
>    port: 2222,
>    tryKeyboard: true,
>    debug: console.log,
>    readyTimeout: 99999,
>    username: 'user',
>    password: 'password'
>  });

put it in it's own directory then in that directory run:

`node init` (leave everything at default)
`npm install ssh2`
`node test.js > out.log`

(I did this on a windows machine so YMMV on the commands, although they should also work on Linux, you will need node installed on that machine, you are trying to connect from)

this should give a log of a connection which you can post, someone here or at https://github.com/mscdex/ssh2 may be able to help. 

Make sure you check logs for passwords/usernames etc before posting

Cant give any guarantees though!

**Comment by peeeeeeek** [comment]
Has anyone managed to get this working on V5R4?
I can connect using SSH in terminal to our System i using the following command.

ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -c 3des-cbc -oHostKeyAlgorithms=+ssh-rsa user@ibmsystemi

Is there a way to connect with these parameters within vscode-ibmi?
