### ISSUE TITLE
Cannot load source member list. ERROR: Column or global variable PARTITION_TEXT not found. SQLSTATE=42703 SQLCODE=-206

### ISSUE THREAD

**Issue by Atomic-Johnson** [halcyon-tech/code-for-ibmi#129]
I have a source object loaded into the member browser and when I click the down arrow to expand it. I get this error: "Column or global variable PARTITION_TEXT not found. SQLSTATE=42703 SQLCODE=-206" and it just says ERROR where my source members should be.

I added "enableSQL":false to the connection settings and it still produces the same error but it loads my source members now and I can edit them.

Running IBM I V7R2M0
db2util v1.0.11-1
Code for IBM i v0.4.1

Let me know if there's any other info I can provide.

Thanks

**Comment by worksofliam** [comment]
Let me get that version of db2util installed and take a look.

**Comment by SJLennon** [comment]
FWIW:  It looks like PARTITION_TEXT was added by PTF according to this page:
 https://www.ibm.com/support/pages/enhanced-qsys2syspartitionstat-catalog
Possibly worthwhile checking if the V7R2 PTF has been applied.
@Atomic-Johnson 
@worksofliam

**Comment by worksofliam** [comment]
@SJLennon Thanks for your help on this one.

@Atomic-Johnson By any chance did you check what he suggested? Thanks!

**Comment by Atomic-Johnson** [comment]
Sorry for the late reply, final exams ate my life a little bit. based on running WRKPTFGRP SF99702  and getting "(No PTF groups found.)" I would say we don't have the PTF that adds that field. However, I updated to v0.4.2 of Code for IBM i and everything works now. Thanks for all of your hard work on this extension!
