### ISSUE TITLE
iASP handling

### ISSUE THREAD

**Issue by sgonchigar** [halcyon-tech/code-for-ibmi#131]
When the source library is located in iASP, it is not finding the source for editing.  I see the source member listed on the left side under "MEMBER BROWSER" but when double clicked, I get an error message CPFA0A9: Object not found. Object is /QSYS.lib/srclibrary.lib/QRPGLESRC.file/srcmember.mbr.

I think, it should look for in /iASP/QSYS.lib/srclibrary.lib/QRPGLESRC.file/srcmember.mbr.

OS is V7R3. source resides in iASP.

**Comment by SJLennon** [comment]
@sgonchigar 
There is a   `"sourceASP":` setting in the connection setting.  See link below--you may have to scroll.  If you have this set correctly, I'm afraid I cannot help further.  I don't have any experience with iASPs nor do I have access to one to test with.
You might want to post your settings.json file.
https://halcyon-tech.github.io/code-for-ibmi/#/?id=connection-settings

**Comment by sgonchigar** [comment]
Thank you @SJLennon. I updated that setting and now I am getting CPFA0A7: Path name too long. CPFA097: Object not copied.
The IFS path is now correct but failed with above message.

**Comment by SJLennon** [comment]
@sgonchigar 
This is beyond my current expertise--I'm not up on VSCODE extension development.
You might look at closed issue #76 in case there is anything in there that would help resolve the problem.
Also in your initial post you seemed to be able to find the full text of CPFA0A9. It might be helpful to post the full text of CPFA0A7, i.e.  the &1 in the Cause below.
 Message . . . . :   Path name too long.                                   
 Cause . . . . . :   Path &1 has one or more components that exceed maximum
   size allowed by the file system.

**Comment by sgonchigar** [comment]
Thank you so much @SJLennon. I went thru #76 and found that I had the iASP name incorrectly. After I updated to the right ASP name I was able to create a source member, edit and compile.  Very nice and helpful extension you guys have created.  Thank you!!!
