### ISSUE TITLE
Do not show certain info messages

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/code-for-ibmi#132]
Specifically `RNF5409` because they're useless

**Comment by SJLennon** [comment]
Why RNF5409 specifically?
`RNF5409: The prototyped call returns a value which is lost when CALLP is used`.

Are you planning to (optionally) exclude all info message?

This is the one I see most:
`RNF7089: RPG provides Separate-Indicator area for file DISPLAY`.

These also come up.
```
RNF7066: Record-Format MSGWNTFYF not used for input or output. (0)
RNF7086: RPG handles blocking for file MSGWNTFYP. INFDS is updated only when blocks of data are transferred. (0)
```

Just curious 😃 
@worksofliam

**Comment by worksofliam** [comment]
@SJLennon maybe we need a way to define which notices to hide? 

I am seeing it way too much when writing code!

What do you think?

**Comment by SJLennon** [comment]
IMost of my career I've routinely ignored info and warning messages on RPG compiles. Once I'd found the filter in the Problems tab in VSCODE I set that to show just errors. This is the same approach I take with RDi.
![image](https://user-images.githubusercontent.com/67484051/118139746-ac984b80-b3d5-11eb-8257-3099e8f35f7f.png)

Granted, it's not perfect:

1. You have to reset it occasionally  but VSCODE now seem to mostly remember the filter settings most of the time.
2. The Problem tab count doesn't take the filter into consideration. (It's still showing 13, above left, which is what catches my eye).
3. The squiggly line highlight still also show up in the code for infos and warnings, regardless of the Filter settings.

For the coding I'm doing now, this works for me.  For those in a major project it might be different.  

If you are going to enhance it, then my thought would be to simply base the hiding on the severity level.  Seems to me that it might be a lot of work and maintenance to base it on message id.

**It would be interesting to see what others thought. Especially the 700+ folk who have installed the extension. Maybe some others will weigh in.**

@worksofliam

**Comment by worksofliam** [comment]
And that works great for hiding issues in the problems tab, but I also want the blue lines to stop appearing under the severity 10 lines. Nonetheless, you have provided some great information.

**Comment by SJLennon** [comment]
Glad to be of assistance...

Here's a suggestion:
Allow hiding by severity level, which should keep most people happy.  But then allow an exception list of message ids that are never hidden. This, I think, would be generally a short list.

@worksofliam

**Comment by worksofliam** [comment]
@SJLennon I might work on _this_ this weekend.. will keep you posted!
