### ISSUE TITLE
UI to edit/maintain actions

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/code-for-ibmi#133]
**Is your feature request related to a problem? Please describe.**

No problem as such, but I do find it might be nicer to have some UI to create new actions instead of having to edit the JSON.

**Describe the solution you'd like**

New UI for:

* Viewing existing actions
* Editing existing actions
* Creating a brand new action

**Comment by SJLennon** [comment]
I think this is a great idea.  It's a bit easy to mess up settings.json.

I'd suggest that you have the option to copy an action to a new name, to make it easier to extend an existing action.
@worksofliam

**Comment by worksofliam** [comment]
This is where I am at so far:

![image](https://user-images.githubusercontent.com/3708366/118409745-f98c5400-b659-11eb-8b0c-1858f3c30132.png)

![image](https://user-images.githubusercontent.com/3708366/118409766-132d9b80-b65a-11eb-9a0b-8eeef525294a.png)

**Comment by SJLennon** [comment]
Looks promising.  Any issue with duplicate names? 
Any possibility of sorting the work with actions list alphabetically?  (I googled "javascript sort json" and it came up with some code but I didn't dig into it.  I don't think unsorted is a killer, but as someone once said "Nothing is impossible if you don't have to code it  yourself."
@worksofliam

**Comment by worksofliam** [comment]
@SJLennon 

Sort is a nice idea. Alphabetical is a nice idea. I'll do that

**Comment by worksofliam** [comment]
Much nicer! 

![image](https://user-images.githubusercontent.com/3708366/118410379-25f59f80-b65d-11eb-9c6f-d325c240dce1.png)

**Comment by worksofliam** [comment]
Can't get the icons to work without Codicons, but I want this feature. For now, we'll ship without the icons.
