### ISSUE TITLE
Add license to package.json

### ISSUE THREAD

**Issue by chrjorgensen** [halcyon-tech/code-for-ibmi#134]
**Is your feature request related to a problem? Please describe.**
It is not possible currently to add this extension to [Open VSX](https://github.com/open-vsx/publish-extensions), since there are no license info in the package.json file.

**Describe the solution you'd like**
Please add the license to the package.json file:
```
"license": "MIT",
```

**Additional context**
When the license is in place, this extension can be added to the Open VSX repository and found in VS Codium and other editors using the extension repository.

See #126 for more original request.

**Comment by worksofliam** [comment]
Will pick this up in the morning.

I have a ton of stuff I want to work on in the coming week and this should be one of them.
