### ISSUE TITLE
Can't open connection dialog

### ISSUE THREAD

**Issue by dferrand** [halcyon-tech/code-for-ibmi#14]
When pressing F1 and choosing "IBMi: Connect" I get the following error:
Command 'IBM i: Connect' resulted in an error
(command 'code-for-ibmi.connect' not found)

code-for-ibmi 0.0.6, VS Code 1.53.2 on linux

**Comment by worksofliam** [comment]
@dferrand That is certainly an odd issue. I am afraid you might have to debug that one yourself since I cannot recreate it.

https://github.com/halcyon-tech/code-for-ibmi#run-from-local

**Comment by getfoundational** [comment]
I have the same issue.  I saw this on the Midrange email list today and did the following steps.
1.  Downloaded and installed VS Code (Version 1.53.2)
2. Installed Code for IBMi Extension
3. Installed IBMi Languages Extension
4. Tried following instructions on main page of this project where is says to press F1 and find 'IBM i: Connect'

When doing that, nothing shows up in the find result.

**Comment by getfoundational** [comment]
I think I solved it.  The 2 extensions I mentioned above appear to be for code highlighting, syntax, etc.

The extension that you need for connections and such is RPG for IBM i here:
https://marketplace.visualstudio.com/items?itemName=HalcyonTechLtd.code-for-ibmi

After installing that, I do see the connection option.

**Comment by barrettotte** [comment]
@dferrand @getfoundational I submitted a PR (https://github.com/halcyon-tech/code-for-ibmi/pull/15) that should resolve this problem on Linux (tested with Ubuntu 20.04.2), it seems to be a small file naming issue that didn't wasn't effecting Windows

**Comment by dferrand** [comment]
Yeah found it too.
File is src/Instance.js and extension.js references src/instance.
It works on windows because the filesystem is not case sensitive
