### ISSUE TITLE
Any issues with IASP?

### ISSUE THREAD

**Issue by AjaykulkarniIBMi** [halcyon-tech/code-for-ibmi#16]
I am able to set up and see my source file and library. However, when I click on some members I don't see these sources.
nothing happens.
I am able to open source on QSYSINC/H.

I am not sure if IASP is an issue? I see all the source code files expanded, it's just that it does open when double clicked.

**Comment by worksofliam** [comment]
Yep. That'd be an ASP issue 👎 

I know the fix. Just got to do it :)

**Comment by worksofliam** [comment]
My plan is to make the ASP a configurable item in the settings.

**Comment by worksofliam** [comment]
@AjaykulkarniIBMi Grab 0.0.8 and see the source ASP config in the settings.
