### ISSUE TITLE
Connect to another server

### ISSUE THREAD

**Issue by szsascha** [halcyon-tech/code-for-ibmi#161]
Is there a chance to disconnect from the current server and connect to another server without starting a new session of VS Code?

**Comment by worksofliam** [comment]
Yes, there is a command to disconnect. ￼

**Comment by SJLennon** [comment]
If you have a connection and try to start another it will first stop you current connection.  Provided you have no open and unsaved files.
@szsascha

**Comment by szsascha** [comment]
Ok, thanks a lot!
