### ISSUE TITLE
Place "Run Action" a the top of the right-click menu with a separator if possible.

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/code-for-ibmi#21]
Not high pty, but once we figure out re-ordering menu items, let's put Run Action at the top and possibly a separator and then the member actions.

**Comment by richardschoen** [comment]
Implementation in .13 looks good but move Run Action to top.

**Comment by worksofliam** [comment]
![image](https://user-images.githubusercontent.com/3708366/109179751-367e3400-7758-11eb-8adb-0dd5b0db8a53.png)

in 0.0.14

**Comment by thebeardedgeek** [comment]
@richardschoen What other actions can you run?

**Comment by richardschoen** [comment]
We renamed Compile to Actions. So pretty much any CL command can be executed along with source member info or without source member info. Actions can be global or tied to a source type.
