### ISSUE TITLE
For Run Action, change completion message since it's no longer just for compiles.

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/code-for-ibmi#23]
After action completes, if not using a compile command the completion message still says:
"Compiled file/member successfully" ot on fail "file/member did not compile."

Couple thoughts for easy change:
"file/member action completed successfully" or on fail "file/member action did not complete successfully."

More complex thought 1:
Possibly put a completion or error message in the settings.json for each action so they can have their own message.

More complex thought 2:
Possibly surface the CPF response message(s) from command completion. 

My ideal answer would be option 2 which might surface the CPF message, but the easy change of message verbiage is good for now also. 

Things to ponder.

**Comment by richardschoen** [comment]
Interestingly I already see the CPF messages on the IBM i Compile Log. Which may need a name change as well to "IBM i Output Log"  or "IBM i Output".

**Comment by worksofliam** [comment]
Changed action result message texts and also renamed channel output
