### ISSUE TITLE
Could I use git?

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/code-for-ibmi#24]
Until now, I copy my source into my home directory (of my ibm i user) and there I make a git.init, so I can use git.

Is there a possibility to use git with your extension?

Many thanks.

**Comment by worksofliam** [comment]
Git does not integrate with the extension.

**Comment by richardschoen** [comment]
Actually it does if you're using my iForgit plugin product for Git source management of IBM i source members.  http://www.iforgit.com
