### ISSUE TITLE
Can Problems Tab be cleared. Continues to grow after several compiles

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/code-for-ibmi#25]
Not sure if this is a VS code thing or not, but messages pile up.

**Comment by worksofliam** [comment]
Can't recreate it. Share a screenshot please

**Comment by thebeardedgeek** [comment]
https://github.com/Microsoft/vscode/issues/66982#issuecomment-699516908
Maybe diagnostics.clear() will help?

I am seeing the same thing. The problems show even after closing the file.

**Comment by thebeardedgeek** [comment]
![image](https://user-images.githubusercontent.com/9466407/109005090-2cccd180-766f-11eb-8571-15de73687e97.png)
The file is closed but the problems are still showing.

**Comment by worksofliam** [comment]
Yes, problems will remain even when the file is closed - this is normal VS Code behavior. Problems only disappear when it compiles successfully. 

Maybe we need to add our own command to clear them.

**Comment by worksofliam** [comment]
This is where the logic is: https://github.com/halcyon-tech/code-for-ibmi/blob/master/src/api/CompileTools.js#L38

**Comment by worksofliam** [comment]
I think the plan is to add a command which will clear the Problems window.

**Comment by poseva** [comment]
Any updates on this ?

> Yes, problems will remain even when the file is closed - this is normal VS Code behavior. Problems only disappear when it compiles successfully.
> 
> Maybe we need to add our own command to clear them.

Is there any chance to somehow use a dummy task that returns successfully so that the problems will be cleared ?

**Comment by poseva** [comment]
I've found an workaround.
**Solution 1** 
(drawback: the Problems pane gets appended with the errors/warnings of the current running task and gets cleared only at the end of task)
Assign to each task the same dummy owner:
```
"owner": "ClearProblemsPaneWorkaround"
```
When executing a task, the Problems pane will be appended with the errors/warnings of the current running task but when the task is completed the Problem pane gets cleared of any previous errors/warnings and only errors/warnings of the current task remain.
**Solution 2**
Create a dummy task to clear the Problems pane and call this before any other task. This dummy task will execute a benign command and a dummy problem matcher and so the Problems pane gets all cleared.
```
 {
            "label": "ClearProblemsPaneWorkaround",
            "presentation": {
                "echo": false,
                "reveal": "silent",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": true
            },
            "type": "shell",
            "command": [
                "exit 0"
            ],
            "problemMatcher": {
                "fileLocation": "relative",
                "pattern": {
                    "regexp": "(ClearProblemsPaneWorkaround)",
                    "file": 1,
                    "line": 1,
                    "message": 2,
                    "severity": 1
                },
                "owner": "ClearProblemsPaneWorkaround"
            },
            "options": {
                 "shell": {
                     "executable": "C:\\Windows\\system32\\cmd.exe",
                     "args": ["/d", "/c"]
                 }
            }
        },
```
P.S.
I'm amazed that this clear Problems pane issue is not fixed even after all this years... and so much discussions around this issue when all of this could have been so simple.
