### ISSUE TITLE
Connect to previous IBM i

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/code-for-ibmi#29]
I can successfully connect using the "Connect to an IBM i" button.  Therefore this issue is not urgent.

However, when I restart VSCODE, I thought I should be able to to use the "Connect to previous IBM i" to avoid some typing.  While it does seem to remember my previous connections, nothing seems to happen, as shown below.
![vscode1](https://user-images.githubusercontent.com/67484051/109054812-56581e00-76ac-11eb-978c-a8ceea686d90.png)
Pressing enter on the highlighted connection, or left clicking, or right clicking result in this: 
![image](https://user-images.githubusercontent.com/67484051/109055256-ed24da80-76ac-11eb-9a8f-383891959a3e.png)
I press "Enter" and nothing happens.

I use VSCODE mainly for playing with node.js and do not consider myself an expert.  So this may be a user error on my part.  Or maybe something in my setup.  This is my settings.json:  (Hmmm.  I don't see why the font suddenly changes after "code-for-ibmi.connections".  Perhaps there is some hex garbage in there.)
`{
    "telemetry.enableTelemetry": false,
    "editor.renderControlCharacters": false,
    "editor.fontFamily": "Cascadia Code, Inconsolata, Lucida Sans",
    "editor.fontLigatures": false,
    "editor.renderWhitespace": "none",
    "editor.cursorStyle": "block",
    "editor.minimap.enabled": false,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "window.zoomLevel": 0,
    "update.mode": "start",
    "compile-hero.disable-compile-files-on-did-save-code": false,
    "compile-hero.generate-minified-html": true,
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "code-for-ibmi.connections": [

        {
            "host": "pub400.com",
            "port": 2222,
            "username": "lennons"
        },
        {
            "host": "ipublic.online",
            "port": 2222,
            "username": "lennons"
        }
    ],
    "code-for-ibmi.homeDirectory": "/home/lennons1",
    "code-for-ibmi.libraryList": "QSYS2,QSYSINC, LENNONS1",
    "code-for-ibmi.logCompileOutput": true,
    "code-for-ibmi.sourceFileList": [
        "QSYSINC/H",
        "lennons1/QTEMP",
        "lennons1/QCLSRC",
        "lennons1/qrpglesrc"
    ],
    "code-for-ibmi.temporaryLibrary": "lennons2",
    "code-for-ibmi.compileCommands": [
    
        {
            "fileSystem": "member",
            "extensions": [
                "rpgle",
                "rpg"
            ],
            "name": "CRTBNDRPG",
            "command": "CRTBNDRPG PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*EVENTF) DBGVIEW(*SOURCE)"
        },
        {
            "fileSystem": "member",
            "extensions": [
                "CLLE",
                "CL"
            ],
            "name": "CRTBNDCL",
            "command": "CRTBNDCL PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*EVENTF) DBGVIEW(*SOURCE)"
        },
        {
            "fileSystem": "member",
            "extensions": [
                "CLP"
            ],
            "name": "CRTCLPGM",
            "command": "CRTCLPGM PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*SOURCE) OUTPUT(*PRINT)"
        }
    ]
}`

**Comment by worksofliam** [comment]
Well, sorry it's not as obvious but that second box is for the password. I will make it mention that - thanks.

**Comment by worksofliam** [comment]
Change is here. Will be available in 0.0.13

**Comment by SJLennon** [comment]
Well duh!  I was pretty sure that I tried putting my password in there, but apparently not.  It does work. Sorry...

**Comment by thebeardedgeek** [comment]
@SJLennon it does make sense for this request... I believe others will run into this as well. Thanks @worksofliam for changing that.

P.S. I like the new icon for the plug-in as well.
