### ISSUE TITLE
Save before Compile Alert Prompt

### ISSUE THREAD

**Issue by thebeardedgeek** [halcyon-tech/code-for-ibmi#34]
When I was compiling today it kept giving me errors with my code. I had made the corrections but was still getting the errors. Finally, I realized that I hadn't saved the changes first and it was trying to compile the last saved changes (which still contained the error).

Can we get a prompt to save if we haven't done that first or have VS Code automatically save first as part of the CRTL + E to compile?

**Comment by worksofliam** [comment]
Great, idea!

**Comment by worksofliam** [comment]
![image](https://user-images.githubusercontent.com/3708366/109198968-da71da80-776c-11eb-8d25-2ee4f811ec56.png)

**Comment by worksofliam** [comment]
Will be out in 0.0.14

**Comment by thebeardedgeek** [comment]
Bro... Nice! Ask and ye shall receive! Thank you.

**Comment by SJLennon** [comment]
Yeah!  This caught me too...  Thanks.
