### ISSUE TITLE
Configuration of SSH connection

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/code-for-ibmi#4]
HI, 

Could you let me configure the port for connecting to my IBM I or Could you let me specify a certificate? 

Because my server on port 22 accept connections only with certificate (because it is open on internet), while on port 2222 it let me connect with user and password.

Many thanks.

**Comment by worksofliam** [comment]
Hey @pabloto!

There is a PR open for this and we hope to get it done today.

**Comment by worksofliam** [comment]
Please upgrade to 0.0.3
