### ISSUE TITLE
Option to enforce double-click to open source member or IFS file. 

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/code-for-ibmi#41]
I find myself single-clicking files and opening them randomly when I really didn't want the file or source member to open. 

If others like single-click open functionality, create a setting called Single-Click-Open.

If enabled, function as does already. 

If disabled, enforce double click opens.

Note: If I were to click a HUUGE file this could be disruptive.

**Comment by worksofliam** [comment]
A nonissue for the extension.

See this SO answer: https://stackoverflow.com/questions/46821368/visual-studio-code-open-file-shortcut-for-double-click

**Comment by richardschoen** [comment]
Not sure what you mean by non-issue ?  I cannot enforce double-clicking to open.

**Comment by richardschoen** [comment]
So people don't need to go elsewhere, here's the setting to add into your settings.json file for VS Code:
**"workbench.list.openMode": "doubleClick"**
