### ISSUE TITLE
Allow me to trigger a QSH script on action for IFS file. 

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/code-for-ibmi#42]
Maybe it already works this way, but I haven't tested yet.

This way if I have a make file or something else PASE/QSH I want to run I can trigger it here. 

An alternative option is I can use my QSHEXEC command to run a QSH/PASE script.

**Comment by worksofliam** [comment]
I think we need to allow both ILE, QSH, and pase commands.

Perhaps the command could be something like this. It defaults to ILE commands:

* `CRTBNDRPG....` - library list will be applied
* `qsh:echo "Running through qsh"` - library list will be applied
* `pase:echo "Running through pase"` - library list will not be applied

**Comment by worksofliam** [comment]
Available in 0.1.3
