### ISSUE TITLE
Allow alpha sorting and possibly filtering on IFS file list 

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/code-for-ibmi#43]
When I listed my root dir /, my files and dirs were not Alphabetically sorted.

**Comment by worksofliam** [comment]
Sorted added.

It is already possible to filter in vscode: 
![image](https://user-images.githubusercontent.com/3708366/109392218-eaaec480-78e8-11eb-9f81-ced0e9db00b6.png)

**Comment by richardschoen** [comment]
How does that work ?

**Comment by SJLennon** [comment]
@richardschoen I learned something new...
Filtering is in the VSCODE documentation.  Go [here](https://code.visualstudio.com/docs/getstarted/userinterface) and scroll down a bit to:

![image](https://user-images.githubusercontent.com/67484051/110147880-2b578380-7daa-11eb-8abd-00fe0e01bf15.png)

**Comment by richardschoen** [comment]
Yep. Very nice isn't it.
