### ISSUE TITLE
On IFS browser, allow me to manually switch to a directory

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/code-for-ibmi#44]
Let's say I want to quickly nav to a directory and download a files or do something with is.  A manual **cd** option would be nice.

This is more of a nice-to-have.

**Comment by worksofliam** [comment]
In 0.1.3 you will be able to F1 -> Change Directory 

Or there is a little button to do the same thing
![image](https://user-images.githubusercontent.com/3708366/109392857-7e35c480-78ec-11eb-91b2-08b416018419.png)
