### ISSUE TITLE
Allow me to download / upload files to my PC with the IFS browser. 

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/code-for-ibmi#45]
It would be nice to quickly download a copy of an IFS file or regular source member for offline editing.

Not high priority, but would be cool

Download selected IFS file:
Right click on IFS file, select download, prompt where to save to locally.

Upload selected IFS file:
Right click IFS file and select upload, prompt for local file to upload. Will replace contents of selected IFS file. 

Upload File by Selecting Upload option on dir itself
Right click dir name, select upload, prompt for file name, upload the IFS file into the selected directory. Prompt for replace if IFS file already exists.

**Comment by worksofliam** [comment]
I'd class this as implemented.
