### ISSUE TITLE
Severity Level in Problems

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/code-for-ibmi#51]
After a compile I see something like this:
![image](https://user-images.githubusercontent.com/67484051/109357859-e59e3680-7850-11eb-828b-136f22a0504f.png)
Would it be possible to:
1) Add the severity level to the message
2) Filter which severity levels we want to see.  
The filter icon does allow various severities, but doesn't seem to have any impact:
![image](https://user-images.githubusercontent.com/67484051/109357773-c901fe80-7850-11eb-9f31-341d0f0b9316.png)

**Comment by worksofliam** [comment]
It looks like the filters do work for me:

![image](https://user-images.githubusercontent.com/3708366/109364289-6f073600-785c-11eb-8344-2772568cdcb5.png)

But I will put the severity in the message also.

**Comment by worksofliam** [comment]
The severity will be displayed from 0.1.2 

![image](https://user-images.githubusercontent.com/3708366/109364394-b55c9500-785c-11eb-913b-3a7e607b525f.png)

**Comment by SJLennon** [comment]
@worksofliam 
Apologies. Filters do seem to work.  My mistake.
