### ISSUE TITLE
SQL tools

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/code-for-ibmi#53]
Something similar to what this Postgres extension provides?

https://marketplace.visualstudio.com/items?itemName=ckolkman.vscode-postgres

Is it worth building this?

**Comment by barrettotte** [comment]
For my typical workday, I've been using a tool like [JetBrains DataGrip](https://www.jetbrains.com/datagrip/) for DB2 for i and MSSQL. This would be a pretty cool feature, but I personally don't know a lot of people writing SQL in VS Code.
So, if this is decently high effort it might not be worth investing time into for a while.

This is just my initial take on it though, I'd be curious to see how many people use SQL tools in VS Code

**Comment by worksofliam** [comment]
Thanks for your input, @barrettotte.

**Comment by worksofliam** [comment]
If we were to build a tree view, here is where we get the data: https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_72/db2/rbafzcatalogtbls.htm

**Comment by worksofliam** [comment]
![image](https://user-images.githubusercontent.com/3708366/109439737-91848500-79fd-11eb-97cb-312362013aa8.png)

**Comment by worksofliam** [comment]
![image](https://user-images.githubusercontent.com/3708366/109440215-68fd8a80-79ff-11eb-863f-95bbd60a2586.png)

**Comment by worksofliam** [comment]
So I made a PR for all that's been done so far & there is a screenshot there of what it looks like. Next up is really getting the specifics down, so I won't release it until it at least has some functionality.

https://github.com/halcyon-tech/code-for-ibmi/pull/59

Would love to hear some ideas that could make the database browser useful.
