### ISSUE TITLE
Quick comments

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/code-for-ibmi#54]
Being able to use Ctrl/Command + FORWARD_SLASH would be nice when editing RPG, CL, etc. I can easily do this one.

Might involve creating a command which looks at the activeEditor, etc.

**Comment by worksofliam** [comment]
Okay, I went ahead and created the commenter but I don't think it's the right way to do it since it doesn't work with the usual `Cmd+/`. 

I couldn't find in the docs where to implement it.. I guess it's tied to an LSP or language implementation?

**Comment by barrettotte** [comment]
@worksofliam do you mind if I steal this one lol? 

https://github.com/barrettotte/vscode-ibmi-languages/issues/67

**Comment by worksofliam** [comment]
@barrettotte yes lol! Please let me know when you've got that deployed so I can remove the dumb functionality I added.

Thanks for your work there!

**Comment by barrettotte** [comment]
@worksofliam Yeah I just happened upon that VS Code documentation page today while fixing another issue. I just have one last bug to fix and I should have everything pushed up here shortly. I'll at you when its ready

**Comment by worksofliam** [comment]
@barrettotte I saw you made two releases, so I'm gonna remove my stuff in prep now.

Thanks!

**Comment by barrettotte** [comment]
@worksofliam  ah yeah my bad, the notification might not have come through on a different issue I closed. It should be all set, thanks!
