### ISSUE TITLE
Diff between two sources

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/code-for-ibmi#57]
This could be a really cool one. Providing the ability to do a different two souces.

Maybe a right-click option on members and streamfiles to select which files to compare?

https://stackoverflow.com/a/63197880/4763757

**Comment by SGI495** [comment]
I agree. Due to the way we work there's often a need to merge code from one source to another. A source comparison feature with merge actions would be really great to have.

**Comment by worksofliam** [comment]
![image](https://user-images.githubusercontent.com/3708366/109590446-03320100-7ada-11eb-86fe-f8bdf5e518ff.png)

Diff functionality added.
