### ISSUE TITLE
Library list per connection

### ISSUE THREAD

**Issue by SGI495** [halcyon-tech/code-for-ibmi#60]
Hi,

Have you considered putting the library list setting on connection level instead of as a global setting (code-for-ibmi.libraryList)? 

I have multiple servers I want to connect to, but they all have different library lists for compilation and not all libraries exist on all servers. This forces me to change the library list setting when I switch servers, since trying to set the library list with a nonexistent library returns an exception (CPF2110).

**Comment by worksofliam** [comment]
Have thought about it. We may or may not do that.. depends on the amount of work requires. Instead, I may add a way to import/export configurations so they're easy to swap out.

**Comment by SGI495** [comment]
Alright, thanks for the info. Are you accepting PRs if I'm able to have a go at it?

**Comment by worksofliam** [comment]
@SGI495 We are totally accepting PRs! I am also happy to help you if you need a hand getting started.

**Comment by Nope7** [comment]
In my experience and my everyday work, this feature is a must. 

I manage a group of 24 of environment and I often need to switch between each environment. 

I think the best solution could be to introduce the ability to store library list PRESETS that should be choosen on a dropdown in the main view in order to switch easly from an environment to another...

Thanks in advance for your GREAT job!

(Thanks Thanks Thanks!)

**Comment by worksofliam** [comment]
@SGI495 I am going to work on this. There will not be a different config per system, but instead a new view where you can select which configuration will use.

E.g. you will be able to store and use different configuation. Each configuration will hold:

* unique name
* unique library list
* home directory
* build library
* source ASP

**Comment by SGI495** [comment]
@worksofliam Alright, sounds good. I started looking at it yesterday but I didn't get much further than analysing how the current implementation was done. I would've probably gone down the path of adding those items (as well as CCSID used for the connection if you don't want UTF-8) to the code-for-ibmi.connections configuration object and populating the values from there when choosing a connection in the quickPicker. However decoupling them of course allows for a many-to-many relationship between connections and configurations, which I really like.

I also had a completely different thought that the home directory could probably be populated from the user profile used for the connection by default. Basically by fetching the HOME_DIRECTORY field from the QSYS2.USER_INFO view. Perhaps better suited for a new issue.

**Comment by worksofliam** [comment]
@SGI495 I went ahead and got the work done this morning. I will make a PR for you to review if you like?

**Comment by SGI495** [comment]
@worksofliam Ah cool, looks almost exactly like what I had imagined! I'll definitely take a look =)

**Comment by worksofliam** [comment]
Awesome. Thank you for your input, btw @SGI495!

**Comment by worksofliam** [comment]
That was a grossly large change, but it had to happen. As merged in #67, each connection (by hostname) will get it's own confuguration. 

It is now out in 0.2.0
