### ISSUE TITLE
Different Library List for OBJECT BROWSER and DATABASE BROWSER

### ISSUE THREAD

**Issue by Nope7** [halcyon-tech/code-for-ibmi#65]
As I wrote in the object, I think that the lists should be different:
- On the list used by the OBJECT BROWSER I should put the libraries in which I store my compiled programs
- On the list used by the DATABASE BROWSER I should put the libraries in which I store my tables and my datas

Is it correct or did I misunderstood how to use the extension? 

Thanks in advance for your great job

**Comment by worksofliam** [comment]
Right now, the object browser and database browser both use the library list for the library/schema list. This can change

**Comment by worksofliam** [comment]
I will separate those lists out after the changes for #60 has been fixed+merged. Thanks!

**Comment by worksofliam** [comment]
Now that different connections get their own settings, this will be possible. Below is a list of changes required. I will get around to it eventually, but here is a list of what's required if someone else does. Thanks! 

### Object Browser

* New connection property`objectLibraryList` for a list of libraries used by the Object Browser
* Object Browser needs buttons to add to that libraries list
* Object Browser needs context menu items to remove libraries (Right click on library -> Remove from list)

### Database Browser

* New connection property`schemaList` for a list of libraries used by the Database Browser
* Database Browser needs buttons to add to that schemas list
* Database Browser needs context menu items to remove schemas (Right click on library -> Remove from list)

### Configuration additions

* `objectLibraryList` and `schemaList` both need to be added to the `code-for-ibmi.connectionSettings` array properties in `package.json` (with defaults)
* `Configuration` class needs to include these two properties in the class constructor (with the same defaults). For example:

```
this.objectLibraryList = base.objectLibraryList || [`QSYS2`];
this.schemaList = base.objectLibraryList || [`SAMPLE`, `QIWS`];
```

**Comment by worksofliam** [comment]
I did it! 0.2.4 includes this fix. Object browser and database browser now get their own settings instead of using the library list.

![image](https://user-images.githubusercontent.com/3708366/109885856-3c3eb280-7c4d-11eb-8ad1-5ed97b5dd998.png)

![image](https://user-images.githubusercontent.com/3708366/109885872-41036680-7c4d-11eb-83a4-e7f3090bd27d.png)
