### ISSUE TITLE
error loading member (error with CPYTOIMPF)

### ISSUE THREAD

**Issue by dariocs** [halcyon-tech/code-for-ibmi#7]
I installed it , I'm connecting  but I have error loading member message , How could I debug or give you more info?
Thanks

**Comment by worksofliam** [comment]
Send us a screenshot + see this for running in debug: https://github.com/halcyon-tech/code-for-ibmi#run-from-local

**Comment by KlausPeterLuttkus** [comment]
Same problem as dariocs:

I'm working on IBM i V7R4, latest ptfs installed. System CCSID: 1141
![23-02-_2021_15-32-20_Error_loading_member](https://user-images.githubusercontent.com/23362564/108858472-7b855780-75ec-11eb-9eaf-982e8e1a4c71.png)

Help would be appreciated
Thanks a lot!

**Comment by worksofliam** [comment]
I am releasing 0.0.6 which will print an error message with the text when you see that. Hopefully, that will help us.

Thanks!

**Comment by dariocs** [comment]
the  error message is "CPD0104  incorrect parameter OUTQ . CPF0006: Errors
occurred in command"
Thanks!


Il Mar 23 Feb 2021, 15:43 barry <notifications@github.com> ha scritto:

**Comment by worksofliam** [comment]
@dariocs What is your temp library in the settings?

**Comment by dariocs** [comment]
my temp library in the settings was QTEMP I changed to MYLIB and  now the
error is
CPF2845: La copia non è stata completata per il codice causa 5.
CPF2817: Il comando di copia si è interrotto a causa di un errore.

Il giorno mar 23 feb 2021 alle ore 17:08 barry <notifications@github.com>
ha scritto:

**Comment by worksofliam** [comment]
@dariocs Yes, you can't use QTEMP. We should note that down.

Are you able to find out what CPF2845 - reason code 5 is? This is coming from `CPYTOIMPF`.

**Comment by dariocs** [comment]
Seems  DTAFMT are not valid.

Message ID . . . . . . : CPF2845 Severity . . . . . . . : 40
Message type . . . . . : Diagnostic

Message . . . . : The copy did not complete for reason code 1.
Cause . . . . . : The Copy From Import File (CPYFRMIMPF) command, or Copy To
Import File (CPYTOIMPF) command could not be completed for reason 1. The
reason codes are:
1 - The CCSID or code page value is not valid.
2 - The field *N in the Field Definition File is not a field in the
TOFILE.
3 - The data for field *N of the TOFILE has a wrong decimal seperator.
4 - The data for field *N of the TOFILE does not allow nulls, or the from
file does not have enough fields for the TOFILE. The TOFILE does not support
nulls.
5 - The delimiters for the DTAFMT(*DLM) are not valid.

**Comment by worksofliam** [comment]
@dariocs What version of IBM i are you running?

**Comment by dariocs** [comment]
@barry  I’m at 7.4  Inviato da Posta per Windows 10 Da: barryInviato: martedì 23 febbraio 2021 19:36A: halcyon-tech/code-for-ibmiCc: dariocs; MentionOggetto: Re: [halcyon-tech/code-for-ibmi] error loading member (#7) @dariocs What version of IBM i are you running?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by worksofliam** [comment]
@dariocs 

This is the command being run to get the member list. You should run it and see what happens. Also, see what you have to change to get it to work.

```
DSPFD FILE(QSYSINC/H) TYPE(*MBR) OUTPUT(*OUTFILE) OUTFILE(MYLIB/MBRLIST)
QSYS/CPYTOIMPF FROMFILE(MYLIB/MBRLIST MBRLIST) TOSTMF('/tmp/THELIST.csv') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL)"
```

**Comment by dariocs** [comment]
Adding FLDDLM(';') instead the default FLDDLM(',')  it  works:

QSYS/CPYTOIMPF FROMFILE(PROVAD/MBRLIST MBRLIST) TOSTMF('/tmp/THELIST.csv')
MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM)
RMVBLANK(*TRAILING)
FLDDLM(';') ADDCOLNAM(*SQL)


Il giorno mar 23 feb 2021 alle ore 21:07 barry <notifications@github.com>
ha scritto:

**Comment by dariocs** [comment]
or Adding FLDDLM(';')   DECPNT(*PERIOD)   also it  works:
QSYS/CPYTOIMPF FROMFILE(PROVAD/MBRLIST MBRLIST)
               TOSTMF('/tmp/THELIST.csv')
               MBROPT(*REPLACE)
               STMFCCSID(1208)
               RCDDLM(*CRLF)
               DTAFMT(*DLM)
               RMVBLANK(*TRAILING)
               FLDDLM(',')
               DECPNT(*PERIOD)
               ADDCOLNAM(*SQL)

the error il caused   using    FLDDLM(';') and  DECPNT(*COMMA) together

Il giorno mer 24 feb 2021 alle ore 08:50 Dario Carnevale <
dario.carnevale.schianca@gmail.com> ha scritto:

**Comment by KlausPeterLuttkus** [comment]
In my case the culprit was the temporary library. i sat it to QTEMP. After changing that to a self created library the display of source members works like a charm.

Thanks for helping!

**Comment by dariocs** [comment]
In my case the default of the command is DECENT(*COMMA ) , i have changed to DECANT(*PERIOD) and it works:
Please , Could you add DECPNT(*PERIOD) to your command?

QSYS/CPYTOIMPF FROMFILE(PROVAD/MBRLIST MBRLIST)
               TOSTMF('/tmp/THELIST.csv')
               MBROPT(*REPLACE)
               STMFCCSID(1208)
               RCDDLM(*CRLF)
               DTAFMT(*DLM)
               RMVBLANK(*TRAILING)
               FLDDLM(',')
               DECPNT(*PERIOD)
               ADDCOLNAM(*SQL)
Thank you

**Comment by worksofliam** [comment]
@dariocs I need you to try and fix this one on your end and make a PR for it, I'm afraid.

Best try getting it working for you first and then we can work together to get it released since I cannot recreate this issue.
