### ISSUE TITLE
CPF3064: Library ILEDITOR not found  - when adding new source file

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/code-for-ibmi#71]
I'm on 0.2.3. The issue occurs after I add a new source file, then try to expand it.  
![image](https://user-images.githubusercontent.com/67484051/109842933-91140600-7c18-11eb-9d63-917648336a27.png)

If I exit VSCODE and restart it, the problem is fixed and I can expand the source file.

**_Note also_** that while trying to document this issue I have managed to add QPRGLESRC several times.  This occurred because I added it, but it didn't show up.  I then added it twice more without it showing up.  Finally, when I added QDDSSRC, the three QRPGLESRCs showed up.  Timing issue maybe...

I've been on various earlier releases and I understand that things are improving rapidly. Thus my settings.json file is somewhat messy which might be contributing to this problem.  There are a lot of lines in low intensity which I believe means they are not referenced and one of these is ""code-for-ibmi.temporaryLibrary" which was an earlier setting..  I see that now that library lists are connection specific (a good change!) there I now have several  "tempLibrary": "ILEDITOR" lines.  

Here's my settings.json file:

<details>
  <summary>Click to expand!</summary>

```
{
    "telemetry.enableTelemetry": false,
    "editor.renderControlCharacters": false,
    "editor.fontFamily": "Cascadia Code, Inconsolata, Lucida Sans",
    "editor.fontLigatures": false,
    "editor.renderWhitespace": "none",
    "editor.cursorStyle": "block",
    "editor.minimap.enabled": false,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "window.zoomLevel": 0,
    "update.mode": "start",
    "compile-hero.disable-compile-files-on-did-save-code": false,
    "compile-hero.generate-minified-html": true,
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "code-for-ibmi.connections": [
        {
            "host": "pub400.com",
            "port": 2222,
            "username": "lennons"
        },
        {
            "host": "ipublic.online",
            "port": 2222,
            "username": "lennons"
        }
    ],
    "code-for-ibmi.homeDirectory": "/home/lennons/qrpglesrc",
    "code-for-ibmi.libraryList": "QSYS2,QSYSINC, LENNONS1",
    "code-for-ibmi.logCompileOutput": true,
    "code-for-ibmi.sourceFileList": [
        "QSYSINC/H",
        "lennons1/QTEMP",
        "lennons1/QCLSRC",
        "lennons1/qrpglesrc"
    ],
    "code-for-ibmi.temporaryLibrary": "lennons2",
    "code-for-ibmi.compileCommands": [
        {
            "fileSystem": "member",
            "extensions": [
                "rpgle",
                "rpg"
            ],
            "name": "CRTBNDRPG",
            "command": "CRTBNDRPG PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*EVENTF) DBGVIEW(*SOURCE)"
        },
        {
            "fileSystem": "member",
            "extensions": [
                "CLLE",
                "CL"
            ],
            "name": "CRTBNDCL",
            "command": "CRTBNDCL PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*EVENTF) DBGVIEW(*SOURCE)"
        },
        {
            "fileSystem": "member",
            "extensions": [
                "CLP"
            ],
            "name": "CRTCLPGM",
            "command": "CRTCLPGM PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*SOURCE) OUTPUT(*PRINT)"
        }
    ],
    "workbench.activityBar.iconClickBehavior": "focus",
    "workbench.list.openMode": "doubleClick",
    "code-for-ibmi.connectionSettings": [
        {
            "host": "pub400.com",
            "sourceFileList": [
                "QSYSINC/H",
                "LENNONS1/TEMP"
            ],
            "libraryList": [
                "QSYS2",
                "QSYSINC"
            ],
            "homeDirectory": "/home/lennons",
            "tempLibrary": "ILEDITOR",
            "buildLibrary": "QTEMP"
        },
        {
            "host": "ipublic.online",
            "sourceFileList": [
                "QSYSINC/QRPGLESRC",
                "LENNONS1/TEMP",
                "LENNONS1/QCLSRC",
                "LENNONS1/QRPGLESRC",
                "LENNONS1/QRPGLESRC",
                "LENNONS1/QRPGLESRC",
                "LENNONS1/QDDSSRC"
            ],
            "libraryList": [
                "QSYS2",
                "QSYSINC"
            ],
            "homeDirectory": "/home/lennons",
            "tempLibrary": "ILEDITOR",
            "buildLibrary": "QTEMP"
        }
    ],
    "code-for-ibmi.actions": [
    
        {
            "type": "member",
            "extensions": [
                "RPGLE",
                "RPG"
            ],
            "name": "Create Bound RPG Program (CRTBNDRPG)",
            "command": "CRTBNDRPG PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"
        },
        {
            "type": "member",
            "extensions": [
                "SQLRPGLE"
            ],
            "name": "Create SQL ILE RPG Program (CRTSQLRPGI)",
            "command": "?CRTSQLRPGI OBJ(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) CLOSQLCSR(*ENDMOD) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"
        },
        {
            "type": "member",
            "extensions": [
                "RPGLE",
                "RPG"
            ],
            "name": "Create RPG Module (CRTRPGMOD)",
            "command": "?CRTRPGMOD MODULE(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"
        },
        {
            "type": "member",
            "extensions": [
                "CMD"
            ],
            "name": "Create Command (CRTCMD)",
            "command": "?CRTCMD CMD(&OPENLIB/&OPNMBR) PGM(&OPNLIB/&OPNMBRC) SRCFILE(&OPENLIB/&OPENSPF) ALLOW(*ALL) CURLIB(*NOCHG) PRDLIB(*NOCHG)"
        },
        {
            "type": "member",
            "extensions": [
                "CMD"
            ],
            "name": "Create Command (Allow Return Variables - CRTCMD)",
            "command": "?CRTCMD CMD(&OPENLIB/&OPNMBR) PGM(&OPNLIB/&OPNMBRC) SRCFILE(&OPENLIB/&OPENSPF) ALLOW(ALLOW(*BPGM *IPGM *BMOD *IMOD) ) CURLIB(*NOCHG) PRDLIB(*NOCHG)"
        },
        {
            "type": "member",
            "extensions": [
                "pf",
                "lf"
            ],
            "name": "Delete File (DLTF)",
            "command": "?DLTF FILE(&OPENLIB/&OPENMBR)"
        },
        {
            "type": "member",
            "extensions": [
                "dspf"
            ],
            "name": "Create Display File (CRTDSPF)",
            "command": "?CRTDSPF FILE(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) SRCMBR(&OPENMBR) RSTDSP(*NO) REPLACE(*YES)"
        },
        {
            "type": "member",
            "extensions": [
                "pf"
            ],
            "name": "Create Physical File (CRTPF)",
            "command": "?CRTPF FILE(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) SRCMBR(&OPENMBR) SIZE(*NOMAX) MAXMBRS(1)"
        },
        {
            "type": "member",
            "extensions": [
                "lf"
            ],
            "name": "Create :Logical File (CRTLF)",
            "command": "?CRTLF FILE(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF)"
        },
        {
            "type": "member",
            "extensions": [
                "CLP",
                "CLLE"
            ],
            "name": "Create CL Program (CRTCLP)",
            "command": "?CRTCLPGM PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OUTPUT(*PRINT) REPLACE(*YES)"
        },
        {
            "type": "member",
            "extensions": [
                "CLP",
                "CLLE"
            ],
            "name": "Create Bound CL Program (CRTBNDCL)",
            "command": "?CRTBNDCL PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*EVENTF) DBGVIEW(*SOURCE)"
        },
        {
            "type": "member",
            "extensions": [
                "GLOBAL"
            ],
            "name": "Create Program (CRTPGM)",
            "command": "?CRTPGM PGM(&OPENLIB/&OPENMBR) MODULE(*PGM) ENTMOD(*FIRST) BNDSRVPGM(*NONE) BNDDIR(*NONE) ACTGRP(*ENTMOD) TGTRLS(*CURRENT)"
        },
        {
            "type": "object",
            "extensions": [
                "GLOBAL"
            ],
            "name": "Delete object",
            "command": "?DLTOBJ OBJ(&LIBRARY/&NAME) OBJTYPE(*&TYPE)"
        },
        {
            "type": "object",
            "extensions": [
                "pgm"
            ],
            "name": "Call program",
            "command": "?CALL &LIBRARY/&NAME"
        }
    ]
}
```

</details>

**Comment by worksofliam** [comment]
Hi @SJLennon 

You are right in that the settings have changed. VS Code should be greying out the settings that are no longer in use. I can see here that in your `code-for-ibmi.connectionSettings`, both hosts have `ILEDITOR` in the `temporaryLibrary`. 

I see before you had `lennons2` in your settings before, so you should change those to match the old one.

Hope that helps!

**Comment by barrettotte** [comment]
@SJLennon I had the library not found issue for 'ILEDITOR' occur as well. For PUB400 at least, this host doesn't let users create libraries. If you change 'ILEDITOR' to your personal library (LENNONS1 ?) then it should resolve the error for PUB400 at least.

@worksofliam I may be wrong, but I think the extension tries to create the temporary library if not exists? The creation fails for PUB400 and causes it not to be found (I think)

**Comment by worksofliam** [comment]
@barrettotte 

That is correct!

https://github.com/halcyon-tech/code-for-ibmi/blob/master/src/api/IBMi.js#L83

Perhaps if the library doesn't exist & couldn't be created, we should default it to their current library? (which we get when we get their library list.)

**Comment by SJLennon** [comment]
I figured I could change the setting.json.  However, I'm not sure why it works after I exit and restart VSCODE.  (I'm guessing that the temporary library isn't used all that often.)

PUB400.COM does not let you create libraries--for very good reasons.  I'm not sure it's a good idea to assume library create authority.  Nor to create a library automatically even if you can.  I think you need to at least let the user override the temporary library name.  Defaulting to *CURLIB might work.  But does everyone have a *CURLIB?  Can't CURLIB be *CRTDFT?  Nothing is simple...

Wasn't there a place to enter the temporary library name on an earlier version?  I don't see anywhere now that I can enter it, except in settings.json.  And it does not seem to be referenced in the extension text. 

@worksofliam @barrettotte

**Comment by worksofliam** [comment]
@SJLennon You can override the `tempLibrary`.

This is from the config you pasted:

```
    "code-for-ibmi.connectionSettings": [
        {
            "host": "pub400.com",
            "sourceFileList": [
                "QSYSINC/H",
                "LENNONS1/TEMP"
            ],
            "libraryList": [
                "QSYS2",
                "QSYSINC"
            ],
            "homeDirectory": "/home/lennons",
            "tempLibrary": "ILEDITOR",
            "buildLibrary": "QTEMP"
        },
```

You need to change the `tempLibrary` there to be something else.

**Comment by SJLennon** [comment]
> p.s. if you had source files from the JSON, you need to refresh manually. If you add them from the member browser (there is a little button on the browser), then it will refresh automatically

I was adding them from the little button in the browser.  I believe the duplicates may have happened because I had settings.json open.  Opening settings.json from File/Preferences/Settings/Extensions seems to mark it as dirty, presumably the "new Object" line below.
![image](https://user-images.githubusercontent.com/67484051/109873288-8b7be780-7c3b-11eb-8288-f65eb8322b91.png)

 If you then click the button in the Member Browser and add a source file, the source file does not appear in the browser.  Clicking the refresh button in the browser does make it show up and you can expand it. At this point it is not showing up in the open settings.json file.
![image](https://user-images.githubusercontent.com/67484051/109873753-312f5680-7c3c-11eb-864b-6a8b9e26c983.png)

If I save settings.json and reopen VSCODE the newly added file is lost, as expected.

If I open settings.json, then do ctrl + Z to undo the New object stuff, then add a new source file, everything works as expected.

I don't know if this is how I got several entries for QRPGLESRC but I suspect it is related.  It probably isn't a major issue because likely most people won't have settings.json open, but I'm reporting it just in case it is useful.

@worksofliam

**Comment by worksofliam** [comment]
@SJLennon thanks for the info. I may open another issue for that. I presume the issue with the temporary library is solved?

**Comment by SJLennon** [comment]
No problem with solving the temporary library issue.   
(I uninstalled the app kind of hoping it would remove it's items, cleaned up my settings.json manually when it didn't, re-installed and edited settings.json.  Good to go.)
