### ISSUE TITLE
Unable to open rpgle files from some locations (due to ASP)

### ISSUE THREAD

**Issue by mdgozza** [halcyon-tech/code-for-ibmi#76]
Firstly, thanks so much for your work on this extension, I am not native to as400 programming but this extension makes it a breeze to review code already written.

I am having difficulties opening files from some locations, they simply do not open. I took the liberty to run this extension locally and console.log the ssh commands to get an understanding of what exactly is failing and why:

Here is what I can provide, hopefully it helps illustrate my problem. 

When double clicking on a file I receive these logs in the extension:
![image](https://user-images.githubusercontent.com/9098106/110022243-ac0a7700-7cf9-11eb-841b-2630648a9aff.png)

Specifically I see the command to be 

```
system "CPYTOSTMF FROMMBR('/QSYS.lib/WLIB.lib/QRPGLESRC.file/CFCRTGCDS.mbr') TOSTMF('/tmp/vscodetemp-oiZyUiJVC3') STMFOPT(*REPLACE) STMFCCSID(1208)"
```
and the result to be:
```
stderr:'CPFA0A9: Object not found.  Object is /QSYS.lib/WLIB.lib/QRPGLESRC.file/CFCRTGCDS.mbr.\nCPFA097: Object not copied.  Object is /QSYS.lib/WLIB.lib/QRPGLESRC.file/CFCRTGCDS.mbr.'
```

Compared to a different directory, which is successful as follows:

![image](https://user-images.githubusercontent.com/9098106/110022766-57b3c700-7cfa-11eb-8064-4c03b8057f69.png)

Any thoughts on how I might be able to debug this further?

**Comment by worksofliam** [comment]
Hi @mdgozza! 

My first question to you is: are you using an ASP on your system? Perhaps the libraries or source file is part of that ASP.

**Comment by mdgozza** [comment]
> Hi @mdgozza!
> 
> My first question to you is: are you using an ASP on your system? Perhaps the libraries or source file is part of that ASP.

Honestly, I have no idea. I'm trying to figure that out now though and will report back. 
Those files do show up inside the extension though, if that helps give any indication.

**Comment by worksofliam** [comment]
When you fetch the member list, look for a property that contains `ASP`. All members in a file would have the same value.

**Comment by worksofliam** [comment]
@mdgozza I just release 0.2.8 which might be able to help you a little bit. I have some questions for you

1. What version of the OS are you on? Are you able to run `SELECT * FROM QSYS2.ASP_INFO`?
2. Do you have yum installed? Are you able to install db2util?

If the answer is yes to both of these, the extension will automatically pick up what ASP the source file is in and that might solve your problem (if this even is an ASP problem....)

**Comment by mdgozza** [comment]
Thanks for getting back to me @worksofliam! 

I was able to run that statement and did get back results. 

| DEVICE\_DESCRIPTION\_NAME | ASP\_NUMBER | ASP\_STATE | ASP\_TYPE | RDB\_NAME |
| :--- | :--- | :--- | :--- | :--- |
| NULL | 1 | NONE | SYSTEM | S10B0706 |
| CF\_PRD\_33 | 33 | AVAILABLE | PRIMARY | S1070DAC |

Not positive of the version of the OS ( I'm looking into figuring that out ), and I do not have yum as I run osx. ( but maybe I could build that db2util tool myself )

**Comment by worksofliam** [comment]
Hey @mdgozza!

Thanks for getting back to me also! Looks like you're on a newer version of IBM i if you can run that statement.

Also, when I said about yum.. I meant yum on IBM i. You can use yum on IBM i to install some open source tools, and db2util is available on there. 

Also, it does look like some of your source lives on another ASP. I would recommend updating the extension to 0.2.8, installing db2util onto your IBM i and hopefully that will solve your problem.

Thanks!

**Comment by mdgozza** [comment]
I see, 

It appears `yum` is not installed on IBM i. At least I don't see it as installed via a regular ssh shell. Installing yum via ACS didn't work out for me due to permissions. 

I may need to reach out internally to see if I can install this tool on our IBM i. I may be stuck with this for a little while.

I suppose the utility you want installed in IBM i allows your vs code extension to query DB2 via ssh, and determine where it should load those files from. ( as I try to understand this problem better )?

**Comment by mdgozza** [comment]
Reviewing your commits, I noticed you added a configuration for ASP's. 
https://github.com/halcyon-tech/code-for-ibmi/blob/master/package.json#L141

which field from the ASP_INFO table should I use, maybe I can hard-code this one for now until I get the utility installed.

**Comment by worksofliam** [comment]
@mdgozza I believe you should use 'CF_PRD_33' in that setting in the meantime.

**Comment by mdgozza** [comment]
Hey @worksofliam 

Looks like anything I specify in that property it is still unable to find that member. I've tried a couple of different things. What does that db2util check for when trying to pull a member, maybe I can try to run the same commands?

![image](https://user-images.githubusercontent.com/9098106/110144292-2abcee00-7da6-11eb-8e79-b5f274be36da.png)

| DEVICE\_DESCRIPTION\_NAME | ASP\_NUMBER | ASP\_STATE | ASP\_TYPE | RDB\_NAME | RESOURCE\_NAME |
| :--- | :--- | :--- | :--- | :--- | :--- |
| NULL | 1 | NONE | SYSTEM | S10B0706 | NULL |
| CF\_PRD\_33 | 33 | AVAILABLE | PRIMARY | S1070DAC | CF\_PRD\_33 |

🤔

**Comment by worksofliam** [comment]
@worksofliam Hmm!!

Would you be able to run `DSPOBJD OBJ(WLIB/QRPGLESRC) OBJTYPE(*FILE)`, take option 5 on the file, and tell me what ASP information you see? Like below.

<img width="964" alt="Screen Shot 2021-03-05 at 11 38 00 AM" src="https://user-images.githubusercontent.com/3708366/110145379-5ab8c100-7da7-11eb-8c1a-42bbc0488f35.png">

Then, also run `wrklnk '/CF_PRD_33*'` and let me know what the result is?

Thanks!

**Comment by mdgozza** [comment]
Very cool, very interesting.

So I ran it and I can see that it's actually CF_DEV_33
![image](https://user-images.githubusercontent.com/9098106/110146406-88523a00-7da8-11eb-9958-9d10967af2ce.png)

I went ahead and changed it in the extension, but got a new error this time:
![image](https://user-images.githubusercontent.com/9098106/110146459-9b650a00-7da8-11eb-8b53-a11ffa710169.png)

**Comment by mdgozza** [comment]
I didn't see your second question until now: I just ran WRKLNK for CF_DEV_33 ( instead of PRD that we saw from the query before )
and got this - looks like a directory
![image](https://user-images.githubusercontent.com/9098106/110147109-48d81d80-7da9-11eb-918c-c8bac453f178.png)

**Comment by worksofliam** [comment]
Haha, that's good then! So that CF_DEV_33 is an ASP where to source lives. So now you know about ASP!

Now, about the 65525 thing - that's another annoying thing. 

Can you run these and let me know?

* `dspsysval QCCSID`
* `dspfd WLIB/QRPGLESRC` and look for `Coded character set identifier` - 2 or 3 pages down.

Basically, if your source file is at 65535, then we can't convert it to UTF8 because 65525 means the encoding is basically unknown and has been inherited from the job it's edited from since it was made.

**Comment by mdgozza** [comment]
It's crazy to me how much can be involved in working with IBM i! 

QCCSID is:
![image](https://user-images.githubusercontent.com/9098106/110237214-a33bc000-7f08-11eb-9697-957df03b01ca.png)


Coded character set identifier:
![image](https://user-images.githubusercontent.com/9098106/110237399-e5b1cc80-7f09-11eb-8472-b7ef4a19e823.png)

Again, I really apperciate your help. I've learned so much from following your instructions alone! Don't think I could have debugged this 😓

**Comment by mdgozza** [comment]
Something else I've noticed while debugging: in the pase command executing function:
https://github.com/halcyon-tech/code-for-ibmi/blob/f86bf7ac9b732cd45f6daeeb944ebc1fa566d210/src/api/IBMi.js#L215 

it seems that it's not properly checking for result code because `code` always comes in as a nested property under `arg1` in my case

![image](https://user-images.githubusercontent.com/9098106/110238044-468ed400-7f0d-11eb-89ea-2d3e0909873b.png)

![image](https://user-images.githubusercontent.com/9098106/110238061-560e1d00-7f0d-11eb-9a5a-b94fa830e527.png)

I was going to change it for you, but then I noticed I can't do that because there is always a failure at the very beginning of a connection with `ILEDITOR` already existing and this causes the extension to not be able to load.

I'm curious for your thoughts on if you'd think it wise to modify the error handling code to throw for bad error codes, and then for debugging maybe even present those error messages in a dialog box? Additionally there can be a set of known noop error codes that could be dismissed like `CPF2111` possibly? 

If so, maybe I could do it 😎

**Comment by worksofliam** [comment]
Hi @mdgozza - that isn't great, but not a game stopper. 

I need one more thing from you. Can you also run a `WRKJOB`, take option 2 (I think.. typing from my phone) and find the CCSID values there?

The real issue is that the CCSID of the source file is 65535. This means the encoding is unknown. That means whenever the source file has been edited by anyone, their editor is likely pretending the encoding is the CCSID of the job (thus why I asked you the CCSID).

My plan from here is to add a new setting into the extension so you can set the CCSID manually in the settings for situations like this. In your case, you would set it to the CCSID that you find from your `WRKJOB` info.

Let me know what you find out.

**Comment by worksofliam** [comment]
@mdgozza I have added a new configuration setting for connections just for you 😄 

1. Find the CCSID your job uses (e.g. `WRKJOB` -> option 2 -> scroll until you find info about your CCSID)
2. Update the extension to 0.3.0 (it should do this automatically)
3. Open up the settings for your connection
4. Add `sourceFileCCSID` as the key and the property will be whatever the CCSID you found is (as a string).

It might look like this (`sourceFileCCSID` is at the bottom).

```json
        {
            "host": "xxx",
            "sourceFileList": [
                "QSYSINC/H",
                "BARRY/QRPGLESRC",
                "BARRY/BADCCSID"
            ],
            "objectBrowserList": [
                "QGPL", "QTEMP", "BARRY" ],
            "databaseBrowserList": [ "QGPL", "SAMPLE", "QIWS" ],
            "libraryList": [ "QGPL", "QTEMP" ],
            "homeDirectory": "/home/xxx",
            "tempLibrary": "ILEDITOR",
            "buildLibrary": "BARRY",
            "sourceFileCCSID": "37"
        }
```

5. Then restart VS Code, reconnect, and try and open the member again.

I also made it print error messages into VS Code if there is an error - much more useful.

**Comment by mdgozza** [comment]
Wooohoo @worksofliam !!! it totally works!

![image](https://user-images.githubusercontent.com/9098106/110340109-e3796c00-7ff6-11eb-8504-1d317e3ec65e.png)

for reference, it looks like there is a property "default coded character set identifier" maybe you can fallback to that if that is available as a property to you in some way if you find 65535.

This is so awesome! 

If there is anyway that I can contribute to the ongoing development of this extension please do let me know. I will be keeping an eye on enhancement issues to see where I might be able to help out. Most immediately maybe I can help out in the UI settings editor, but it's tricky for me to know what is important to be editable ( maybe you can sketch something out? ) 😅 

Anyways, really looking forward to working with you more 🥇

**Comment by worksofliam** [comment]
Hey @mdgozza no problem! 

I would love to write the fallback, but I gotta figure out how to get that other CCSID first!

As for enhancements.. I am not sure! There is a lot I want to do myself and also don't know where to start 😆 

Looking forward to hearing from you again :) Of course raise any issues if you have them.
