### ISSUE TITLE
Add Checkbox to CustomUI

### ISSUE THREAD

**Issue by priceaj** [halcyon-tech/code-for-ibmi#77]
I am trying to implement password saving for servers using the ExtensionContext.Secrets API.

I have this working, but I'd like to make this optional on the login form... but I can't work out how to add a checkbox to the UI.

I tried adding a vscode-checkbox to the CustomUI, and I can get it to render on the form, but it doesn't seem to be active, I cant check the box, or tab into it

Any ideas?

**Comment by worksofliam** [comment]
Let me take a look and see if I can get it in for you: :+1:

**Comment by worksofliam** [comment]
@priceaj Also should mention I am changing the `loadPage` API to return a promise...

**Comment by priceaj** [comment]
That probably won't affect the changes I am making, basically I'm just storing the password using:  

context.secrets.store(`${message.data.username}@${message.data.host}`, `${message.data.password}`);

When you are storing the connection profile in settings.

Then on loading it, it checks to see if there is a stored password, using 

context.secrets.get(`${username}@${host}`)

If not it reverts back to the exiting prompt.

One thing I did notice when you come to save details for an existing connection was that you only check to see if the host is unique.

It's possible that you may want to have different logins for the same host, but currently it looks like if you already have a host set up with one user, then it will not save the connection settings for another. 

(I realise I am hijacking my own issue here, so I can raise another if you want to keep track of it)

**Comment by worksofliam** [comment]
This is going to sound crazy, but I can't get either the checkbox OR the select box to behave correctly. This is a pain.

**Comment by worksofliam** [comment]
@priceaj Well this sucks but I think I am going to hold off adding any more functionality from that framework. In fact, I'd like to replace it ASAP but my CSS knowledge is not good enough.

But I wanted to make you aware of this PR: https://github.com/halcyon-tech/code-for-ibmi/pull/75/files#diff-ea1b156b05428480e0b9b8c79b0fd64eb0e5e5a7204b40ccefd57c4d88a2a161R326

Turns out the vscode theme is accessible via CSS variables.. meaning we could build our own thing. I am gonna look into it some more, but I think this has a lot of potential.

**Comment by priceaj** [comment]
Okay, glad to know it wasn't just me!

**Comment by priceaj** [comment]
I think it may be a problem with the copy of the framework you have in the repo, I installed it as a node module 

npm i @bendera/vscode-webview-elements

then repointed the source (onDiskSrc) to the bundled.js file in 

node_modules\@bendera\vscode-webview-elements\dist\

I then added checkbox as a valid type in customUI and added the code and element and the checkbox seems to work with that 

However, it looks like the way a checkbox works is by having the relevant field appear on the submitted data on the form, the value attribute seems to remain constant. Since you are just reading the value attribute of the form items directly from the page on submit, rather than processing any submitted form data, it's always getting posted with a fixed value.

Looking around, looks like you can read the value of the Checked element of the checkbox instead of the value as per: https://stackoverflow.com/questions/11599666/get-the-value-of-checked-checkbox.

If I get a chance I'll implement

**Comment by priceaj** [comment]
I've implemented in https://github.com/priceaj/code-for-ibmi/tree/secure-password-storage but it's a bit hackey

**Comment by worksofliam** [comment]
@priceaj this is awesome. The problem with the non module, which is what I used first, is that it also ships lots of little svgs. This bloats the extension size by a bunch and won't let you deploy because of it.

We might have to start looking at how to bundle (webpack) some of the extension to reduce file count.

**Comment by worksofliam** [comment]
@priceaj You can see the this error from the deploy action:

```
This extension consists of 317 files, out of which 101 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
Publishing halcyontechltd.code-for-ibmi@0.2.8...
```

https://github.com/halcyon-tech/code-for-ibmi/runs/2036959529?check_suite_focus=true#step:5:7

**Comment by worksofliam** [comment]
You can even see it locally if you run the `package` command: 

```
liam.allan@MacBook-Pro-2 ibmi-code % vsce package
This extension consists of 317 files, out of which 101 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /Users/liam.allan/Documents/ibmi-code/code-for-ibmi-0.2.8.vsix (317 files, 1.08MB)
```

**Comment by worksofliam** [comment]
Great news @priceaj - I got webpack working!! Looks like we can ship these large things after all :) I will be pushing this up later.

```
ibmi-code % vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> code-for-ibmi@0.2.8 vscode:prepublish /Users/liam.allan/Documents/ibmi-code
> webpack --mode production

asset extension.js 410 KiB [emitted] [minimized] (name: main) 2 related assets
cacheable modules 913 KiB 71 modules
16 modules
webpack 5.24.3 compiled successfully in 6931 ms
 DONE  Packaged: /Users/liam.allan/Documents/ibmi-code/code-for-ibmi-0.2.8.vsix (30 files, 560.52KB)
 INFO  
```

**Comment by priceaj** [comment]
I'll get my change in when it's up then!

**Comment by worksofliam** [comment]
@priceaj Pushed up within the hour, friend

**Comment by worksofliam** [comment]
@priceaj Make sure to bring in the latest changes I put into master. That contains the stuff for webpack! You should be good to go :)

**Comment by priceaj** [comment]
Created PR #82 to add the checkbox.

Not implemented the password saving yet, as I realised there is no easy way to change it at present e.g. if a password expires

I think we could do do with a better way of maintaining the connections as mentioned in #68, then we could add functions to delete and update passwords from connections on there
