### ISSUE TITLE
I can't open file in ifs browser

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/code-for-ibmi#79]
HI, 

I can't open stream file from ifs browser, I click on my files, but it doesn't happen nothing.

**Comment by worksofliam** [comment]
Can you open the file from another editor? RDi? EDTF?

**Comment by pabloto** [comment]
Yes, I can.
Before your wonderful extension I share my home directory with samba and then from visual studio code I edit my programs in my home directory without any problem.
The only thing I prefer with my "homemade method"  is that I have made from ssh a git init into my home directory (I have install git through yum) and so I can use git. But I have to copy my program from the source file to my home, and then a copy revert for my collegues...

**Comment by worksofliam** [comment]
The next best thing I can do is add some better error messages to the file system handlers to write some error messages if there are any. 

When that's done, I will report back here and let you know. In the meantime, feel free to debug the extension yourself to figure it out.

**Comment by pabloto** [comment]
I have syslog active on my ibm I, and looking at this log I see:

Mar  5 17:37:27 MYSYSTEM auth|security:info sshd[7133]: Starting session: subsystem 'sftp' for paolos from 192.168.0.141 port 53565 id 1
Mar  5 17:37:27 MYSYSTEM auth|security:info sftp-server[8055]: session opened for local user paolos from [192.168.0.141]
Mar  5 17:37:27 MYSYSTEM auth|security:info sftp-server[8055]: open "/tmp/vscodetemp-oVf17UWfZf" flags READ mode 0666
Mar  5 17:37:27 MYSYSTEM auth|security:info sftp-server[8055]: close "/tmp/vscodetemp-oVf17UWfZf" bytes read 4614 written 0
Mar  5 17:37:27 MYSYSTEM auth|security:info sftp-server[8055]: session closed for local user paolos from [192.168.0.141]
Mar  5 17:37:27 MYSYSTEM auth|security:info sshd[7133]: Close session: user paolos from 192.168.0.141 port 53565 id 1

Could you help this?

**Comment by worksofliam** [comment]
I am afraid this doesn't help me much. It looks like it's opening a temporary file (there are lots of those) and then the connection is closing.

I will add some error messages within the next day and that might help us if you're not able to debug the extension.

**Comment by pabloto** [comment]
How can I debug the extension?

**Comment by worksofliam** [comment]
Check out these few steps:

https://github.com/halcyon-tech/code-for-ibmi#run-from-local

**Comment by pabloto** [comment]
Why you don't use sshfs for editing stream file?

**Comment by pabloto** [comment]
This can help?

<img width="1717" alt="Schermata 2021-03-05 alle 18 19 23" src="https://user-images.githubusercontent.com/9719313/110150255-54463b80-7ddf-11eb-9a71-fd0abea97616.png">

**Comment by pabloto** [comment]
(node:95463) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by worksofliam** [comment]
You are still free to use SSH FS. We download a copy of the IFS to local machine, which is where you make your edits. I am afraid I am not getting much out of that screenshot. I will take a look a bit later on.

**Comment by pabloto** [comment]
I think I found the error in Instance.js when I try to open a stream file the variable path doesn't start with a / so instead of passing through row 182 it goes to 184.
In debug I correct path with the full path '/home/myuser/myfile.xxx and so it let me see the stream file.

<img width="2160" alt="Schermata 2021-03-05 alle 19 13 21" src="https://user-images.githubusercontent.com/9719313/110156113-dd14a580-7de6-11eb-9ff0-eaccef36ae6c.png">

**Comment by worksofliam** [comment]
@pabloto I think I found the issue. Basically if you're home directory is a `.` then it doesn't seem to open correctly.

I'll fix this up tonight. Thanks!

**Comment by worksofliam** [comment]
@pabloto The work around is to correct your home directory (F1 -> IBM i: Change directory)

**Comment by worksofliam** [comment]
@pabloto Did you solve it?

**Comment by pabloto** [comment]
I Liam, I don't know, now it works without doing nothing... Have you change something?
Many thanks. 
I'd like very much this extension!

Great work!

**Comment by pabloto** [comment]
I see the change in the latest release! 
Good night!
