### ISSUE TITLE
DATABASE BROWSER: Sort alphabetically

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/code-for-ibmi#80]
I don't consider this urgent.
This is my first experiment with the DATABASE BROWSER. 
My list of files/tables doesn't have a discernible sort sequence.  It would be nice if it could be sorted alphabetically.
 
![image](https://user-images.githubusercontent.com/67484051/110150569-68714500-7dad-11eb-9758-9d9c97ff2fa0.png)

**Comment by worksofliam** [comment]
Added order by and will be available in 0.2.10
