### ISSUE TITLE
IFS BROWSER - Show hidden files?

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/code-for-ibmi#81]
Currently hidden files are not shown, for example, **.profile**.  Should they be shown?  
Not a high priority; just mentioning it.
![image](https://user-images.githubusercontent.com/67484051/110171340-949abf00-7dc9-11eb-923d-612b47c78848.png)
![image](https://user-images.githubusercontent.com/67484051/110171955-7a151580-7dca-11eb-88bb-d104cd4e0cb6.png)

**Comment by worksofliam** [comment]
Easy to do. I can take it :)

**Comment by worksofliam** [comment]
Will be available in 0.2.10
