### ISSUE TITLE
Crazy idea: Display File renderer?

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/code-for-ibmi#84]
I wonder what people might think of a display file renderer in a webview? It's a crazy idea. Would it even be worth it?

Would love to hear some thoughts.

**Comment by pabloto** [comment]
Hi Liam, I think this could be a good idea, many directors dislike IBM I for the green screen, If you invent some strategies to wrap the millions of display file to something more web friendly this could be great. But please something more efficient then Hats...

**Comment by SJLennon** [comment]
Am I right in assuming you are thinking of emulating the 5250 data stream?  If so, I'm not sure how it fits into this extension.  And I believe it might be quite challenging to do.  Personally, I'd rather see work on content assist (if that is even feasible and maintainable), or integrating a debugger.

**Comment by worksofliam** [comment]
@SJLennon Incorrect. It was actually just going to render the 5250 DDS so you can see it visually while editing it.

**Comment by priceaj** [comment]
RDi has this feature... so not so crazy!

**Comment by worksofliam** [comment]
@priceaj I was thinking we could use something like [canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) to build it? I've personally used [Konva](https://konvajs.org/) before, which is just a nice wrapper.

Have you any ideas?

**Comment by priceaj** [comment]
The only canvas tool I know of is [paper.js](http://paperjs.org/), but it's not something I'm very familiar with

**Comment by worksofliam** [comment]
@priceaj paper.js is awesome, but maybe too complex for a simple text and line renderer? Maybe one day if we want to make it do funny things it could be neat though.
