### ISSUE TITLE
The connection tab is empty

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/code-for-ibmi#86]
HI there's a problem with the connection tab, it's empty

<img width="1468" alt="Schermata 2021-03-08 alle 12 28 42" src="https://user-images.githubusercontent.com/9719313/110315790-09f4d280-800a-11eb-90c5-2d2914051c2d.png">

**Comment by worksofliam** [comment]
What version of the extension are you on?

**Comment by worksofliam** [comment]
Me too. Might be an issue with webpack.

**Comment by worksofliam** [comment]
I would recommend downgrading to 0.2.8 for the time being.

Thanks

**Comment by pabloto** [comment]
For me isn't a problem, connect to previous works, today I install the extension to a colleague and I edit the vscode setting by hand.

**Comment by worksofliam** [comment]
@priceaj I just thought i'd let you know about this issue. I can't believe I didn't catch it - webpack issues.

Basically, the `path.join` doesn't work anymore because we bundle everything with webpack, and therefore the source is missing.

**Comment by worksofliam** [comment]
@priceaj Yes, only after it's been packaged up. But nevermind, I've got it fixed and tested - will be releasing tonight.

**Comment by priceaj** [comment]
Oh fair enough, well done on the quick turnaround then!

**Comment by worksofliam** [comment]
Please upgrade to 0.3.1. This issue has been resolved.
![image](https://user-images.githubusercontent.com/3708366/110386688-9b763b80-802e-11eb-9e68-e3d3714f1f7f.png)
