### ISSUE TITLE
RPGLE linter

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/code-for-ibmi#87]
**Describe the solution you'd like**
I think it would be super nice to implement a basic linter for free-format RPGLE. Checking configurable rules and showing the hints in the editor.

**Describe alternatives you've considered**
I believe the only other alternative, other than some paid products, is to run the compiler with `*NOGEN` which takes time.

**Comment by worksofliam** [comment]
Is this really part of the language tools? #32

**Comment by SJLennon** [comment]
Is it a bit like #64?  There I advocated for a Verify command that ran the compiler.  Don't know the effort involved, but it seems to me that might be a quicker option and would automatically keep up with enhancements to the compiler.
@worksofliam

**Comment by worksofliam** [comment]
No. It's to do some basic syntax checking on your source code (for example, indentation, like in the photo)

![image](https://user-images.githubusercontent.com/3708366/110412900-f6258c80-805a-11eb-8d70-09eb063f9871.png)

https://stackoverflow.com/a/8503586/4763757

**Comment by SJLennon** [comment]
So stylistic errors mainly.  Indention checking would be nice.  Check for missing ; maybe, though could be tricky.  I think any type of END statement without a ; would qualify as a warning.
