### ISSUE TITLE
Connecting with only one Connection

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/code-for-ibmi#88]
This is **not** urgent, just might be a convenience.
If I have just one IBM i to connect to e.g.
![image](https://user-images.githubusercontent.com/67484051/110403352-f4ec6380-804a-11eb-8fd1-26911109595f.png)
Could it just jump immediately to the password prompt so I don't have to click the connection.
![image](https://user-images.githubusercontent.com/67484051/110403460-1c433080-804b-11eb-90f9-a1ad23017797.png)

**Comment by worksofliam** [comment]
A nice to have idea for sure. I can work on this :)
