### ISSUE TITLE
In Problems, make Filter settings sticky

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/code-for-ibmi#90]
When I compile I get a result like this, because all three filter options (Errors, Warnings, Infos) are checked.
![image](https://user-images.githubusercontent.com/67484051/110408979-82808100-8054-11eb-92f8-92aa1ab385a2.png)

Virtually all the time I would be working with only Errors checked, rarely caring about warnings and infos.  And probably also Show Active File Only Checked.  It would be nice to make these settings "sticky" across sessions.

(Interesting, it appears the the Show Active File Only setting is retained across sessions.)

(In the screen shot there are 14 problems--10 are in another file.)

**Comment by worksofliam** [comment]
Sadly I think this is a vscode specific thing and not something that can be controller by an extension. I will close for now since there isn't much we can do about this I believe. :(

**Comment by SJLennon** [comment]
I think I will put in an enhancement request to the VSCODE folk. They seem to have been doing some work on errors and filtering lately.
@worksofliam

**Comment by SJLennon** [comment]
Further, FWIW:
If I keep the folder with the JavaScript errors open, then connect to the IBM i and do a compile, the the filter settings are retained.
