### ISSUE TITLE
Proposal instead of DSPFD

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/code-for-ibmi#91]
Hi, 

I have a source file with more then 12000 member, so when I open it from your extension it takes some minutes before doing list, why don't  you use sql to get this information:

I try the dspfd from command line and it take 3 minutes, while this sql take me a few seconds:

` With Listmember (Library, srcname, rowsize,  Json_member) As (
    Select trim(System_Table_Schema), trim(System_Table_Name), trim(char(avgrowsize)), Json_Object(
             'memberName' Value System_Table_Member, 'type' Value Source_Type,
             'text' Value Partition_Text
           )
      From Qsys2/Syspartitionstat
      Where Table_Schema = 'MYLIB'
            And Table_Name = 'QRPGLESRC'
  )
    Select Json_Object(
      'library' Value Library, 'file' Value srcname, 'rowLength' value rowsize,
      'memberList' Value Json_Arrayagg(
        Json_member Format Json
      ) 
    )
    From Listmember
    group by library, srcname, rowsize;`

the output will be in json so you can stop producing stream files in /tmp and take only the information needed.

Let me know if is possible.

**Comment by worksofliam** [comment]
@pabloto It will defo be possible, but only for those that have `db2util` installed. So maybe I could write the code to use this statement and fallback to the older way if required.

**Comment by worksofliam** [comment]
@pabloto Looks like this might get us what we need:

```
select 
  System_Table_Member,
  Source_Type,
  Partition_Text
 From Qsys2/Syspartitionstat Where Table_Schema = 'QSYSINC' And Table_Name = 'H'
```

Although it's missing two things:

* Record length
* ASP name or number

**Comment by pabloto** [comment]
avgrowsize contains record length, while the asp you can get it from sysschemas, in join

`With Listmember (Library, Srcname, Rowsize, Json_Member) As (
    Select Trim(System_Table_Schema), Trim(System_Table_Name), Trim(
             Char(Avgrowsize)), Json_Object(
             'memberName' Value System_Table_Member, 'type' Value Source_Type,
             'text' Value Partition_Text
           )
      From Qsys2/Syspartitionstat
      Where Table_Schema = 'MYLIB'
            And Table_Name = 'QRPGLESRC'
  )
  Select Json_Object(
      'library' Value Library, 'file' Value Srcname, 'rowLength' Value Rowsize, 'asp' value iasp_number,
      'memberList' Value Json_Arrayagg(
        Json_Member Format Json
      )
    )
    From Listmember, SYSSCHEMAS 
    WHERE SCHEMA_NAME = LIBRARY 
    Group By Library, Srcname, Rowsize, iasp_number;
`

without json:

`
Select System_Table_Schema, System_Table_Name, Avgrowsize, Iasp_Number,
       System_Table_Member, Source_Type, Partition_Text
  From Qsys2/Syspartitionstat, Sysschemas
  Where Table_Schema = 'MYLIB'
        And Table_Name = 'QRPGLESRC'
        And Schema_Name = System_Table_Schema
`

**Comment by worksofliam** [comment]
Yup, it looks like 

```
Select 
  Avgrowsize, 
  Iasp_Number, 
  System_Table_Member, 
  Source_Type, Partition_Text 
From Qsys2.Syspartitionstat, Qsys2.Sysschemas 
Where 
  Table_Schema = 'QSYSINC' And 
  Table_Name = 'H' And 
  Schema_Name = System_Table_Schema
```

**Comment by worksofliam** [comment]
Any idea why DSPFD is giving me an ID of `1`for the ASP but the SQL is giving me `0`?

![image](https://user-images.githubusercontent.com/3708366/110517552-ffedd500-80d8-11eb-99f3-47d94a2266f1.png)

![image](https://user-images.githubusercontent.com/3708366/110517653-20b62a80-80d9-11eb-83da-a8413f93be20.png)

**Comment by worksofliam** [comment]
I just tested - it seems that 0 and 1 are the same in this instance. So... if the member ASP is `0` or `1` then it's in the base ASP.

Thanks @pabloto!

I will on this tonight.

**Comment by pabloto** [comment]
Thanks to you
