### ISSUE TITLE
Provide an OUTLINE View

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/code-for-ibmi#92]
**Describe the solution you'd like**
VSCODE produces an OUTLINE view for various file types. e.g. JavaScript and HTML in my experience.  
![image](https://user-images.githubusercontent.com/67484051/110512297-16912d80-80d3-11eb-8356-5c9888f20f86.png)

I think this might be an addition that many would like and find useful.  Priority would be free-form RPG.

**Describe alternatives you've considered**
It has been touched on in #32 and #64.  I'd just like to make it more visible. **Others may wish to weigh in on the value of an outline.**

**Comment by worksofliam** [comment]
@SJLennon I am going to close this as a dupe, as would come under #32. I'd rather keep all comments in one place for this functionality, rather than multiple issues for the same thing.
