### ISSUE TITLE
Manipulating Library List for Compiles

### ISSUE THREAD

**Issue by getfoundational** [halcyon-tech/code-for-ibmi#98]
Hello,

I am trying to find a solution to a challenge I have with our current coding environment.  We have code for many customers all stored in different libraries.  Each customer may have different files and such that are needed for their programs to compile.  As such, when working on a customers code, I normally just edit my library list to put their library near the top, make code changes, compile, and then move on to another customer and do the same thing.

I know that per connection you can specify a library list, but creating 50 connections seems like a bad approach if I can avoid that.  Instead I am looking for some way to either dynamically use the source code library (i.e. **CUSTSLIB**/QRPGLESRC) to set my LIBL when I am editing their code or perhaps set the LIBL at compile time as part of the compile command or link a couple commands together as part of the compile command.  I would be OK setting the customer's library at the top of the LIBL and then removing it after the compile as well, if that might work.

Just looking for some ideas on how to best approach/overcome this situation.

Thank you.

**Comment by worksofliam** [comment]
Okay. Maybe we need to make the `&BUILDLIB` variable accessible via the member compile, that way you can easily change it AND use it in your compile commands.

We also need a way to switch between multiple library lists in a connection?

**Comment by getfoundational** [comment]
Having the `&BUILDLIB` variable available sounds like a good option if it could then be changed and used in a way to manipulate the library list at compile time.

I wonder if having multiple library lists per connection could be linked to the member list so that you could assign a given library list you've defined to the member list so it's used in the compiles of anything in that member list?

Or perhaps in my specific situation for example, you could actually use the `&BUILDLIB` variable in the library list itself and it would be substituted at compile time, sort of like this:

`QTEMP`  
`QGPL`   
`&BUILDLIB`
`LIB1`
`LIB2`

For me, the rest of my library list is the same all the time and only the one library needs to be in the library list in the same relative position all the time so this last option would be excellent for me, although I am unsure of the usefulness for everyone else.

Thank you.

**Comment by worksofliam** [comment]
@getfoundational I love the idea of using the build liv in both members and in the library list!

I might make a commanf to easy change the build library also: F1 -> Change build library

**Comment by getfoundational** [comment]
Sounds great!  Thanks for taking this in to consideration.

**Comment by worksofliam** [comment]
@getfoundational will be available in 0.3.5.
